### ISSUE TITLE
divide class not work

### ISSUE THREAD

**Issue by chenar-x** [antfu/unocss#100]
<div class="grid grid-cols-3 divide-x divide-green-500">
  <div>1</div>
  <div>2</div>
  <div>3</div>
</div>

**Comment by chenar-x** [comment]
divide is work on unocss.antfu.me, but not work on my local demo(vite with unocss)

**Comment by imbeard** [comment]
I have a similar problem (using unocss with vite) divide class is not working as expected, I'm using latest unocss version

you can check it out here:
user: animal
pwd: efficient

https://steadfast-spiral.localsite.io/
