### ISSUE TITLE
Property `colors` does not exist on type `{}`

### ISSUE THREAD

**Issue by ydcjeff** [antfu/unocss#108]
When I try [this example](https://github.com/antfu/unocss#extend-theme) with TypeScript, it occurs a type error.

[Reproduction](https://stackblitz.com/edit/vitejs-vite-l3dwl2?file=vite.config.ts&terminal=dev)

**Comment by antfu** [comment]
https://github.com/antfu/unocss/blob/851625af2501bf3773770da89f500bcd31b2331f/packages/preset-uno/src/rules/filters.ts#L49

https://github.com/antfu/unocss/blob/d0911f66082ea2d3859658c131c632288db563e8/packages/preset-uno/src/rules/color.ts#L21-L27

UnoCSS is agnostic to the theme object, you need to specify the types via generic.
