### ISSUE TITLE
Text-transform rules doesn't work

### ISSUE THREAD

**Issue by ztxone** [antfu/unocss#109]
uppercase, capitalize, lowercase seems to doesn't work. Even trough the shortcut

unocss v0.9.0
vitesse-nuxt3 template
same with vitesse-lite (also tested with unocss v0.4.9 and v0.7.7)

**Comment by userquin** [comment]
see https://github.com/antfu/unocss/blob/main/packages/preset-uno/src/rules/static.ts#L57:
```ts
export const textTransforms: Rule[] = [
  ['case-upper', { 'text-transform': 'uppercase' }],
  ['case-lower', { 'text-transform': 'lowercase' }],
  ['case-capital', { 'text-transform': 'capitalize' }],
  ['case-normal', { 'text-transform': 'none' }],
]
```

**Comment by antfu** [comment]
I intentionally didn't support them is I thought Tailwind's convention is too general - but giving the fact that we are already trying to support all utilities from Tailwind, I am fine to have them. PR welcome

**Comment by ztxone** [comment]
> see https://github.com/antfu/unocss/blob/main/packages/preset-uno/src/rules/static.ts#L57:

How to make it work? In my nuxt.config.ts i've already using presetUno()

export default defineNuxtConfig({
  buildModules: [
    '@vueuse/core/nuxt',
    '@unocss/nuxt',
    '@pinia/nuxt',
  ],
  unocss: {
    presets: [
      presetUno(),
    ],
  },
})

**Comment by userquin** [comment]
just use `case-upper`, `case-capitalize`...

**Comment by ztxone** [comment]
> @ztxone just use `case-upper`, `case-capitalize`...

ohh) Sorry for that silly question. 

Big thanks for rapid reply!
