### ISSUE TITLE
Build(*.[hash].css): hash in filename does not change when the content is changed

### ISSUE THREAD

**Issue by alukos** [antfu/unocss#110]
### Reproduce

- build project (`dist/assets/index.e3e4a563.css`)
- add `dist/` to git index and commit
- change someone class in App.vue:template 
- build again and in git state: `modified:   dist/assets/index.e3e4a563.css`

### Expected 
name change for file with another content

### Checked
I tried to reproduce the error in
- [vite-plugin-windicss:example:vanilla-esm](https://github.com/windicss/vite-plugin-windicss/tree/main/examples/vanilla-esm)
- [vite-plugin-windicss:example:vue](https://github.com/windicss/vite-plugin-windicss/tree/main/examples/vue)
but everything works out correctly there

### Blocking
I can't deploy on a server with static caching, for example, on Heroku.

**Comment by iamkhan21** [comment]
Hello, @antfu !
This issue still there.

Before modification:
![image](https://user-images.githubusercontent.com/18110747/161435923-0971eef1-9e23-4b1c-9103-bd51b6e5e598.png)

After:
![image](https://user-images.githubusercontent.com/18110747/161435916-a9e434df-6612-4a3c-9d80-06baa3e038d4.png)

**Comment by bluwy** [comment]
I can reproduce the issue too based on a report at https://github.com/vitejs/vite/issues/8500. The issue has a repro at https://github.com/aimergenge/reproduce-vite-plugin-pages
