### ISSUE TITLE
UnoCSS not reload after change unocss.config.js

### ISSUE THREAD

**Issue by mzaini30** [antfu/unocss#115]
Hi, I use UnoCSS CLI.

When I change shortcuts in unocss.config.js, UnoCSS CLI not reload. So, I stop pnpm dev and start again.

How to auto compile UnoCSS CLI while unocss.config.js modified?

Thanks...

**Comment by antfu** [comment]
/cc @johannschopplich if you want to pick it up, here is how the vite plugin doing it for you to reference

https://github.com/antfu/unocss/blob/134150039784a2110404e0a6d9622580cbc716f2/packages/vite/src/config-hmr.ts#L15-L23

**Comment by johannschopplich** [comment]
@antfu I take on the task. 🙂
