### ISSUE TITLE
The debug panel flashes when use with @unocss/runtime

### ISSUE THREAD

**Issue by YunYouJun** [antfu/unocss#135]
When I introduced the runtime CDN, the fan buzzed and the debug panel flashed all the time.

You can try [this | codepen](https://codepen.io/YunYouJun/pen/porYJee).

https://user-images.githubusercontent.com/25154432/142587725-6b0d0952-9880-4f87-9345-0fe3ad0f1dab.mov

**Comment by chu121su12** [comment]
I think this is related to #194.

**Comment by antfu** [comment]
Should be fixed in v0.15.3 and here is a working demo: https://codepen.io/antfu/pen/eYGNXGo
