### ISSUE TITLE
UnoCSS work with Tailwind or other preprocessors by just enabling the icons preset

### ISSUE THREAD

**Issue by productdevbook** [antfu/unocss#138]
I'm especially looking forward to this feature for nuxt 3. 🥰

**Comment by electroheadfx** [comment]
what do you mean by other preprocessors ? in what preprocessors uno doesn't work ?

**Comment by antfu** [comment]
You can already do it,

```ts
UnoCSS({
  presets: [presetIcons()]
})
```

or in Nuxt

```ts
buildModules: [
  '@unocss/nuxt',
],
unocss: {
  uno: false,
  preflight: false,
  icons: true,
}
```

**Comment by productdevbook** [comment]
vite used

```
UnoCSS({
  presets: [presetIcons()]
})

```
console.log 
`[unocss] entry module not found, have you add `import 'uno.css'` in your main entry?`

**Comment by antfu** [comment]
You will need to add `import 'uno.css'` in your entry

**Comment by productdevbook** [comment]
<img width="583" alt="CleanShot 2021-12-01 at 09 12 15@2x" src="https://user-images.githubusercontent.com/38668796/144181519-1c30d4b2-fc0c-42e9-8425-d2aff68ac172.png">

iam added some problem

**Comment by wommy** [comment]
im getting this too,

```
[unocss] entry module not found, have you add `import 'uno.css'` in your main entry?
```

with [solidjs/ts-unocss](https://github.com/solidjs/templates/tree/master/ts-unocss)

**Comment by veritem** [comment]
Hi @wommy  install the latest version of unocss
We fixed that a few weeks ago

**Comment by wommy** [comment]
i was on version 0.26.2 which as of now is only 10 days old

but the update did fix it, ill patch the solidjs starter soon

**Comment by blooddrunk** [comment]
> 

Is possible that when using `tailwindcss`(with `uno: false` of course), I can still make variants with icon classes like `hover:i-twemoji-face-with-tears-of-joy` work?

**Comment by blooddrunk** [comment]
> You can already do it,
> 
> ```ts
> UnoCSS({
>   presets: [presetIcons()]
> })
> ```
> 
> or in Nuxt
> 
> ```ts
> buildModules: [
>   '@unocss/nuxt',
> ],
> unocss: {
>   uno: false,
>   preflight: false,
>   icons: true,
> }
> ```

Is possible that when using tailwindcss(with uno: false of course), I can still make variants with icon classes like hover:i-twemoji-face-with-tears-of-joy work?

**Comment by productdevbook** [comment]
> > You can already do it,
> > ```ts
> > UnoCSS({
> >   presets: [presetIcons()]
> > })
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > or in Nuxt
> > ```ts
> > buildModules: [
> >   '@unocss/nuxt',
> > ],
> > unocss: {
> >   uno: false,
> >   preflight: false,
> >   icons: true,
> > }
> > ```
> 
> Is possible that when using tailwindcss(with uno: false of course), I can still make variants with icon classes like hover:i-twemoji-face-with-tears-of-joy work?

I tried now, it doesn't work for me.

` <div class="dark:i-ph-moon-duotone i-ph-sun-duotone" />`

**Comment by antfu** [comment]
@productdevbook the `dark:` variant is implemented in the preset-uno (preset-mini more precisely). You can either copy the code to implement only the dark variant or import only variants from preset-uno

**Comment by AndrewBogdanovTSS** [comment]
Still getting this issue with Storybook, though uno.css is imported 
![image](https://user-images.githubusercontent.com/2766448/196031986-20a838c8-0434-4f1e-89b6-8777aa38d109.png)

**Comment by AndrewBogdanovTSS** [comment]
Ok, the issue seems to be in ordering of imports, when I moved import 'uno.css' to the top of the file the issue was resolved

**Comment by CODPHISH** [comment]
> im getting this too,
> 
> ```
> [unocss] entry module not found, have you add `import 'uno.css'` in your main entry?
> ```
> 
> with [solidjs/ts-unocss](https://github.com/solidjs/templates/tree/master/ts-unocss)

i got this problem when use `vercel dev` start local project，but use vite it will works fine

**Comment by xarthurx** [comment]
I'm getting this too.


`vite.config.js`:

```
export default defineConfig({
  plugins: [
    unocssPlugin(),
    unocss(),
    {
      ...(
        mdx({
          jsxImportSource: "solid-js",
          jsx: true,
          providerImportSource: "solid-mdx",
          rehypePlugins: [rehypeHighlight, remarkGfm],
        })
        //
      ),
      enforce: "pre",
    },
    solid({
      adapter: (await import("solid-start-static")).default(),
      extensions: [".mdx", ".md"],
      ssr: true,
    }),
  ],

  ssr: {
    external: ["ag-grid-solid"],
  },
});

```
