### ISSUE TITLE
Preset icons not working with CSS variants?

### ISSUE THREAD

**Issue by kissu** [antfu/unocss#143]
Hello! 👋🏼 

I've started using [Vitesse](https://github.com/antfu/vitesse) and removed [`unplugin-icons`](https://github.com/antfu/unplugin-icons) in favor of [`@unocss/preset-icons`](https://github.com/antfu/unocss/tree/main/packages/preset-icons), removed the default icon settings with the following
```js
import Unocss from 'unocss/vite'
import presetIcons from '@unocss/preset-icons'

Unocss({
  presets: [
    presetIcons({
      prefix: 'i-',
      scale: 4,
      extraProperties: {
        display: 'inline-block'
      }
    })
  ],
 })
 ```
 
So, the icons are working great but the `dark` and `hover` variants do nothing with the following template
```html
<button class="i-carbon-sun dark:i-carbon-moon" />
<div class="i-twemoji-grinning-face-with-smiling-eyes hover:i-twemoji-face-with-tears-of-joy" />
```
 
![image](https://user-images.githubusercontent.com/5133074/142637761-142c7dd3-9ee4-4f0d-b096-a194f003b507.png)

As you can see, the `"... dark:i-carbon-moon"` next to Vue's logo is totally ignored.

I've also tried with `presetAttributify`, but no more success on this one.

The following of course works great
```html
<button class="i-carbon-sun" v-if="isDark" />
<button class="i-carbon-moon" v-else />
 ```
 
 Tell me if you need a repro on top of those explanations!

**Comment by antfu** [comment]
Do you use system preferenced dark for `.dark` in html?

**Comment by kissu** [comment]
Did not changed the `script` section in `index.html`
```html
<script>
  (function() {
    const prefersDark = window.matchMedia && window.matchMedia('(prefers-color-scheme: dark)').matches
    const setting = localStorage.getItem('vueuse-color-scheme') || 'auto'
    if (setting === 'dark' || (prefersDark && setting !== 'light'))
      document.documentElement.classList.toggle('dark', true)
  })()
</script>
```

And everything works well with `isDark`.

**Comment by antfu** [comment]
That's weird, I see https://github.com/antfu/vitesse-lite is working as expected. Can you cross-reference to see if there is anything misconfigured?

**Comment by antfu** [comment]
Oh I see, you didn't enable presetUno - which is where the variants comes from.

**Comment by kissu** [comment]
I wasn't sure that I needed that too, thought icons could be used by themselves + Windi's variants, but I guess that they are not tied in the same way.
It works tho, thanks! 🙏🏼

**Comment by antfu** [comment]
If you really want variants but not the utilities, you can do:

```ts
Unocss({
  presets: [
    presetIcons({
      prefix: 'i-',
      scale: 4,
      extraProperties: {
        display: 'inline-block'
      }
    })
  ],
  variants: presetUno().variants
 })
```
