### ISSUE TITLE
Custom theme colors with dashes or numbers don't work

### ISSUE THREAD

**Issue by pheuter** [antfu/unocss#144]
Same problem if color name contains numbers.

[Repro](https://unocss.antfu.me/?html=DwBwBAxgNghgznAvAIgEYHMC0A7A9gE3gAtkA%2BAYVylwCcwB3ASwBcjcBXZsQuI4AehCkAUKEiwEKDJiatMPEhSq0GLIt2IChQA&config=JYWwDg9gTgLgBAbzgEwKYDNgDtUGEJaYDmcAvnOlBCHAOQCuWEAxgM6u0BQnqAHpLBQYAhvQA28NJhz5CwIgAoEnOHBgALVCFQAuRCtVxmEMdFZ7lhw7SbJhrdbT20AxOnQAGLx9oAaA1a0AO7AGgC0dg5OdG6e3lxWpAZJpACUQA&options=N4IgzgLgTglgxhEAuaBXApgXyA)

```html
<p class="bg-nodash">Color without dash</p>
<p class="bg-with-dash">Color with dash</p>
```

```js
import { defineConfig } from 'unocss'

export default defineConfig({
  theme: {
    colors: {
      'nodash': '#ff0000',
      'with-dash': '#ff0000'
    }
  }
})
```

**Comment by antfu** [comment]
With dash you should do something like:

```ts
import { defineConfig } from 'unocss'

export default defineConfig({
  theme: {
    colors: {
      'nodash': '#ff0000',
      'with': {
        'dash': '#ff0000'
      }
    }
  }
})
```
