### ISSUE TITLE
`Unknown word` error from CSS generated by uno

### ISSUE THREAD

**Issue by pheuter** [antfu/unocss#146]
```
[plugin:vite:css] /__uno.css:9:28: Unknown word
/__uno.css:9:28
7  |  .flex{display:flex;}
8  |  .grid{display:grid;}
9  |  .row-\{row\.id\}{grid-row:{row.id};}
   |                              ^
10 |  .relative{position:relative;}
11 |  .absolute{position:absolute;}
```

I'm getting the error above and having a difficult time figuring out what piece of code is causing it. I've grepped for any possible `row` classes throughout the codebase and can't find any. I also do not have the attributify preset enabled.

**Comment by userquin** [comment]
@edwardnyc can you take a look at this? If you cannot, I can fix it.

**Comment by userquin** [comment]
@pheuter I cannot reproduce the problem on playground and also using `vitesse-lite` template, the tests I included are (with 0.11.0 and 0.11.3 versions of unocss):

```vue
// /src/components/Footer.vue
<template>
  <nav text-xl mt-6 grid grid-rows-4 gap-2>
    <button class="icon-btn !outline-none row-1" @click="toggleDark()">
      <div v-if="isDark" i-carbon-moon />
      <div v-else i-carbon-sun />
    </button>

    <a
      class="icon-btn row-3"
      i-carbon-logo-github
      rel="noreferrer"
      href="https://github.com/antfu/vitesse-lite"
      target="_blank"
      title="GitHub"
    />
  </nav>
</template>
```

also using `grid-row-1`  and `grid-row-3`, also the variants for `col-N` changing also `grid-rows-4` with `grid-cols-4`.

**Comment by pheuter** [comment]
@userquin This issue went away when I explicitly added `**/node_modules/**` to the `exclude` Unocss config property. I believe it had something to do with unocss trying to parse the [carbon](https://carbon-svelte.vercel.app/) library I'm using, and something in that library is prob triggering this weird `row` generation error.

**Comment by userquin** [comment]
@pheuter can you provide a small repro and so we can debug it?

**Comment by userquin** [comment]
@pheuter you can also clone this repo and file a PR with the lib: https://github.com/userquin/unocss-vitesse-tester

**Comment by userquin** [comment]
@pheuter the repro I provide is using `"@iconify-json/carbon": "^1.0.11"`

**Comment by pheuter** [comment]
@userquin https://github.com/pheuter/unocss-repro

**Comment by userquin** [comment]
uhmm, using `svelte`, maybe some problems with `vite-plugin-svelte` plugin, I'll check it rn.

**Comment by userquin** [comment]
> @userquin https://github.com/pheuter/unocss-repro

Do you have a discord account?

**Comment by userquin** [comment]
repo cloned `pnpm install && pnpm run dev` and working (node `16.13.0 LTS`)

![imagen](https://user-images.githubusercontent.com/6311119/142734730-b8931358-3a8e-4b53-b773-b5b7ed7c5ec7.png)

**Comment by pheuter** [comment]
Look at the cuss generated by uno, it has that broken grid row syntax.

**Comment by userquin** [comment]
![imagen](https://user-images.githubusercontent.com/6311119/142734859-99ca07f5-ccc7-4b92-ab9e-2c3f5a9e28e3.png)

**Comment by userquin** [comment]
<details>
<summary>Generated <strong>/__uno.css</strong> </summary>
<p>
<pre>
import { createHotContext as __vite__createHotContext } from "/@vite/client";import.meta.hot = __vite__createHotContext("/__uno.css");import { updateStyle, removeStyle } from "/@vite/client"
const id = "/__uno.css"
const css = "/* layer: default */\n.p0{padding:0rem;}\n.p1{padding:0.25rem;}\n.m-4{margin:1rem;}\n.\\!inline{display:inline !important;}\n.inline{display:inline;}\n.block{display:block;}\n.hidden{display:none;}\n.b,.border{border-width:1px;border-style:solid;}\n.tabsById,.tabs\\2c ,.tabs\\.update\\(_,.tabs,.tabpanel,.tablist,.tableSortable\\2c ,.tableSortable\\.set\\(sortable\\),.tableSortable,.tablerow\\.\\$set\\(tablerow_changes\\),.tablerow\\.\\$on\\(,.tablerow_changes\\.id,.tablerow_changes\\.class,.tablerow_changes\\.\\$\\$scope,.tablerow_changes,.tablerow,.tableheader\\.\\$set\\(tableheader_changes\\),.tableheader\\.\\$on\\(,.tableheader_changes\\.disableSorting,.tableheader_changes\\.\\$\\$scope,.tableheader_changes,.tableheader,.tablehead\\.\\$set\\(tablehead_changes\\),.tablehead_changes\\.\\$\\$scope,.tablehead_changes,.tablehead,.tablecontainer\\.\\$set\\(tablecontainer_changes\\),.tablecontainer_spread_levels\\[i\\]\\),.tablecontainer_spread_levels\\.length,.tablecontainer_spread_levels,.tablecontainer_props\\2c ,.tablecontainer_props,.tablecontainer_changes\\.\\$\\$scope,.tablecontainer_changes,.tablecontainer,.tablecell\\.\\$set\\(tablecell_changes\\),.tablecell\\.\\$on\\(,.tablecell_changes\\[,.tablecell_changes\\.colspan,.tablecell_changes\\.\\$\\$scope,.tablecell_changes,.tablecell,.tablebody\\.\\$set\\(tablebody_changes\\),.tablebody_changes\\.\\$\\$scope,.tablebody_changes,.tablebody,.table\\2c ,.table\\),.table\\.\\$set\\(table_changes\\),.table_levels\\[i\\]\\),.table_levels\\.length,.table_levels,.table_data\\),.table_data,.table_changes\\.zebra,.table_changes\\.useStaticWidth,.table_changes\\.stickyHeader,.table_changes\\.sortable,.table_changes\\.size,.table_changes\\.\\$\\$scope,.table_changes,.tabindex\\2c ,.tabindex\\*\\/,.tabindex\\(value\\),.tabindex\\(\\),.tabindex\\:,.tabindex,.tabId\\2c ,.tabId,.tabbable\\[index\\]\\.focus\\(\\),.tabbable\\.length,.tabbable\\.indexOf\\(document\\.activeElement\\),.tabbable,.tab,.tabsById\\2c {-moz-tab-size:4;-o-tab-size:4;tab-size:4;}\n.grid{display:grid;}\n.grid-cols-2{grid-template-columns:repeat(2, minmax(0, 1fr));}\n.row-\\{row\\.id\\}{grid-row:{row.id};}\n.row-\\{row\\.id\\}\\\\\\\\\\\\{grid-row:{row.id}\\\\\\;}\n.row-1{grid-row:1;}\n.gap-4{grid-gap:1rem;gap:1rem;}\n.relative{position:relative;}\n.fixed{position:fixed;}\n.visible{visibility:visible;}\n.resize{resize:both;}\n.outline{outline-style:solid;}\n.transition{transition-property:color, border-color, background-color, flex-grow, flex, flex-shrink, caret-color, font, gap, opacity, visibility, z-index, font-weight, zoom, text-shadow, transform, box-shadow, backround-position, left, right, top, bottom, object-position, max-height, min-height, max-width, min-width, height, width, border-width, margin, padding, outline-width, outline-offset, font-size, line-height, text-indent, vertical-align, border-spacing, letter-spacing, word-spacing, stroke, filter, backdrop-filter, fill, mask, mask-size, mask-border, clip-path, clip;transition-timing-function:cubic-bezier(0.4, 0, 0.2, 1);transition-duration:150ms;}\n.filter{--un-blur:var(--un-empty,/*!*/ /*!*/);--un-brightness:var(--un-empty,/*!*/ /*!*/);--un-contrast:var(--un-empty,/*!*/ /*!*/);--un-grayscale:var(--un-empty,/*!*/ /*!*/);--un-hue-rotate:var(--un-empty,/*!*/ /*!*/);--un-invert:var(--un-empty,/*!*/ /*!*/);--un-saturate:var(--un-empty,/*!*/ /*!*/);--un-sepia:var(--un-empty,/*!*/ /*!*/);--un-drop-shadow:var(--un-empty,/*!*/ /*!*/);filter:var(--un-blur) var(--un-brightness) var(--un-contrast) var(--un-grayscale) var(--un-hue-rotate) var(--un-invert) var(--un-saturate) var(--un-sepia) var(--un-drop-shadow);}\n.blur{--un-blur:blur(8px);}\n.table{display:table;}\n.transform{--un-rotate:0;--un-scale-x:1;--un-scale-y:1;--un-scale-z:1;--un-skew-x:0;--un-skew-y:0;--un-translate-x:0;--un-translate-y:0;--un-translate-z:0;transform:rotate(var(--un-rotate)) scaleX(var(--un-scale-x)) scaleY(var(--un-scale-y)) scaleZ(var(--un-scale-z)) skewX(var(--un-skew-x)) skewY(var(--un-skew-y)) translateX(var(--un-translate-x)) translateY(var(--un-translate-y)) translateZ(var(--un-translate-z));}\n@keyframes __un_qm{0%{box-shadow:inset 4px 4px #ff1e90, inset -4px -4px #ff1e90}100%{box-shadow:inset 8px 8px #3399ff, inset -8px -8px #3399ff}}\n.\\?{animation:__un_qm 0.5s ease-in-out alternate infinite;}"
updateStyle(id, css)
import.meta.hot.accept()
export default css
import.meta.hot.prune(() => removeStyle(id))
await fetch("/__unocss_ready/1637427753917")
</pre>
</p>
</details>

**Comment by pheuter** [comment]
<img width="1819" alt="Screen Shot 2021-11-20 at 12 05 44 PM" src="https://user-images.githubusercontent.com/92698/142734986-c2fd7059-8c7d-4596-94db-02888dd9aa8e.png">

**Comment by userquin** [comment]
there is no error on client and server: maybe is something the svelte carbon library table adds to the generated component.

**Comment by pheuter** [comment]
If you add postcss processing, like autoprefixer, it'll throw compiler errors because the css generated by uno is invalid.

**Comment by userquin** [comment]
so the problem is that something is adding the `row-` entry and `unocss` rule will transform it, I'll check how to remove or alias that rule.

**Comment by userquin** [comment]
ok, I'm adding validation for `grid-row` and `grid-column` value on the rules.

**Comment by antfu** [comment]
![image](https://user-images.githubusercontent.com/11247099/142736644-b5f26e8a-95ee-4437-b089-b06f35436988.png)

Yes, I belive this is a false postive

**Comment by userquin** [comment]
I'll add some regex using this https://developer.mozilla.org/en-US/docs/Web/CSS/grid-column#values:

![imagen](https://user-images.githubusercontent.com/6311119/142736693-bd45e6cd-ed9b-4dd6-867e-45905e3021d2.png)

![imagen](https://user-images.githubusercontent.com/6311119/142736678-a2d39449-ec93-407f-b083-73d87dc445f3.png)
