### ISSUE TITLE
How to vite unocss/preset-icons change used name `unoicon` 

### ISSUE THREAD

**Issue by productdevbook** [antfu/unocss#149]
iam nuxt3 used Unoicon used. But storybook vite dont see, because vite dont see auto component Unoicon. How to change vite name used ? 

vite storybook dont see icon, nuxt3 working.
<img width="691" alt="CleanShot 2021-11-20 at 09 41 12@2x" src="https://user-images.githubusercontent.com/38668796/142717275-34cd4139-7016-4a33-9111-271005f60fe8.png">

**Comment by antfu** [comment]
You can just use Div, UnoIcon is essential a div alias for semantic purpose

**Comment by productdevbook** [comment]
Can you add a feature to turn on and off creating the unoicon component on the nuxt side? I will add it as a component myself. https://github.com/antfu/unocss/blob/main/packages/nuxt/runtime/UnoIcon.vue

**Comment by antfu** [comment]
https://github.com/antfu/unocss/blob/f69e11b1f734f0ef462eccd0c9a51ee8133f5a55/packages/nuxt/src/index.ts#L28-L34
