### ISSUE TITLE
Dead Attributify Mode link in README

### ISSUE THREAD

**Issue by elazar** [antfu/unocss#154]
The Attributify Mode link on [this line](https://github.com/antfu/unocss/blame/2b4e4a23cc9a1520441da05b6f8a5aec425d0818/README.md#L115) is dead; it references a nonexistent `#attributify-mode` anchor.

[This link](https://github.com/antfu/unocss/tree/main/packages/preset-attributify#attributify-mode) may be a sufficient replacement for the purpose?

**Comment by antfu** [comment]
Mind sending a quick PR? Thanks
