### ISSUE TITLE
Will @unocss/preset-uno (19KB/71KB) be really tree-shakeable?

### ISSUE THREAD

**Issue by lkj4** [antfu/unocss#159]
[Bundlephobia](https://bundlephobia.com/package/@unocss/preset-uno@0.11.6) says yes for the latest version. But I'm wondering how this will behave in reality because how should the build pipeline know what to keep and what not if main usage is via class strings, such as `class='bg-black'`.

Edit: Ok, I think the build step can know about what is used (I assume) since uno is one step in the build (or not) but then I could image that after using just some typical classes most of the preset-uno bundle will be included, right?

**Comment by antfu** [comment]
If you use UnoCSS on the build, the size doesn't matter to you at all. The only chance you will need to care about the size is using the CDN runtime which compares to [Tailwind's 72KB and Windi's 56KB](https://twitter.com/antfu7/status/1453382270216118273), I don't think it's something to concern atm.

**Comment by lkj4** [comment]
> If you use UnoCSS on the build, the size doesn't matter to you at all. 

Because it will be tree-shaken or not?

> compares to Tailwind's 72KB and Windi's 56K

I compare it rather to twind (13KB) or using the og Tachyons unstripped (13.7KB).

But again, I'd like to use uno in the build step and will the not-used class be excluded from the build. Would be great if you could confirm this and if yes, how is this accomplished.

**Comment by wheatjs** [comment]
unocss will only generate classes that you use. There are no classes to exclude because those classes don't even exist.

**Comment by wheatjs** [comment]
If you are still confused take a look at the playground https://unocss.antfu.me/

The Output CSS is the only thing that will be shipped in your production code, nothing else.

**Comment by lkj4** [comment]
Yeah right, thanks for clarifying (not "excluded" but "generated" is the right term).

IRL usage: Since those classes are reflected by rule arrays, will most of the bundle be included after using typical classes? So, I can assume that at least 10-15KB, gzipped, will be used?

**Comment by lkj4** [comment]
Ok thanks forget my last question! 🙂
