### ISSUE TITLE
Unable to use @unocss/preset-icons with nuxt3

### ISSUE THREAD

**Issue by jd-0001** [antfu/unocss#165]
Hi,

I followed this [guide](https://github.com/antfu/unocss/tree/main/packages/nuxt) but I am unable to render icons.

Here's codesandbox: https://codesandbox.io/s/broken-dawn-8yhzf?file=/app.vue

**Comment by jd-0001** [comment]
codesandbox is not working, give me a minite

**Comment by antfu** [comment]
Refer to https://github.com/antfu/vitesse-nuxt3 fo the setup
