### ISSUE TITLE
Icons are not rendering if we get icons list from another file

### ISSUE THREAD

**Issue by jd-0001** [antfu/unocss#166]
Hi, it's me again. Sorry for disturbing you.

I checked `vitesse-nuxt3` and managed to render icons using unocss. After that, I tried to integrate it into my existing project where I get the list of icons from another `.ts` file and render them using `v-for`. (I am rendering vertical nav menu from the list of objects, like vuepress but w/ icons)

The problem is icons are not rendered which are defined in that `.ts` file. However, if we already define/render some of them in `.vue` file then icons get rendered but the unique icons which are not everywhere other than that `.ts` file aren't get rendered.

I hope, I am helping you in making unocss more robust and not wasting your time. 🙏🏻 

Here's CodeSandbox link: https://codesandbox.io/s/vibrant-resonance-d263v?file=/app.vue

Regards.

**Comment by antfu** [comment]
Yes by default `.ts` is not scanned by UnoCSS, you can either add `/* @unocss-include */` comment in the file or include all the `.ts` files by passing the `include` option.

**Comment by jd-0001** [comment]
Both approaches work. Thanks.

If we add all the `.ts` files in the `include` option will it hit the performance? even in dev?

**Comment by jd-0001** [comment]
Also, with pure css icons I am getting missing icons at first glance like in the below video:

https://user-images.githubusercontent.com/47495003/143030458-ddd23d62-2355-4041-bc87-d2bc23b11dbb.mov

I am wondering in your playground, this is not the case. So how do you handle it?

**Comment by antfu** [comment]
> If we add all the .ts files in the include option will it hit the performance? even in dev?

Theoretically, it would, but given the fact that UnoCSS is really fast, it would not be noticeable.

**Comment by chuoke** [comment]
> Yes by default `.ts` is not scanned by UnoCSS, you can either add `/* @unocss-include */` comment in the file or include all the `.ts` files by passing the `include` option.

This should be docs.

**Comment by antfu** [comment]
> This should be docs.

Indeed. @chuoke do you mind sending a PR adding it? Thanks!

**Comment by chuoke** [comment]
> Indeed. @chuoke do you mind sending a PR adding it? Thanks!

Hope I can, but I don't know anything about it other than what you pointed out.

**Comment by jd-0001** [comment]
@antfu @chuoke I will

**Comment by jd-0001** [comment]
#227

**Comment by Avaray** [comment]
> Yes by default `.ts` is not scanned by UnoCSS, you can either add `/* @unocss-include */` comment in the file or include all the `.ts` files by passing the `include` option.

Dear lord! I spent entire three days trying to solve missing icons by refactoring my code. I thought that was the issue.
Finally found this page. Thanks!
