### ISSUE TITLE
missing `translate-x-full` and `translate-y-full`

### ISSUE THREAD

**Issue by userquin** [antfu/unocss#167]

**Comment by chris-zhu** [comment]
Can i use this way to resolve the issue? i think `fraction` should be surport `full` (`full` == `100%`  except `rounded-full`). However, this will generate new properties, such as `m-full`  `p-full` ...  them don't exist in  tw and windicss.

![image](https://user-images.githubusercontent.com/42139754/143553190-871bf931-85f1-42e2-80af-471b1bc950fb.png)

**Comment by UltraCakeBakery** [comment]
> Can i use this way to resolve the issue? i think `fraction` should be surport `full` (`full` == `100%` except `rounded-full`). However, this will generate new properties, such as `m-full` `p-full` ... them don't exist in tw and windicss.
> 
> ![image](https://user-images.githubusercontent.com/42139754/143553190-871bf931-85f1-42e2-80af-471b1bc950fb.png)

@userquin is the goal of your issue #124 to _only_ have all tailwind classes, or to just have all tailwind classes available on top of the extras unocss comes with?

**Comment by userquin** [comment]
@chris-zhu add it to fraction function, we review it when the PR pushed, just add a hint/comment on the PR.

@UltraCakeBakery both, the main goal is to align with tw and windi. Issue #124 was my fisrt attempt to find all missing or misaligned rules here we should add/update (a task I need to do a new review, so feel free to add on #124 if you find some missing or misaligned rules).
