### ISSUE TITLE
The response design does not support '<md' and '@md'

### ISSUE THREAD

**Issue by Johnson-hd** [antfu/unocss#181]
![image](https://user-images.githubusercontent.com/15664509/143978594-947ce6b3-4139-40a0-b72d-c1c5bf0e3390.png)

windicss support '<md' and '@md', but unocss not.

This is my unocss configuration in nuxt3. I have 3 designs(pc | ipad | mobile)
shortcuts: [
  [/^pc-([a-z]+)-(\d+)$/, ([, w, d]) => `xl:${w}-[${d}px] lg:${w}-[${(1600 / 1920) * d}px]`],
  [/^ipad-([a-z]+)-(\d+)$/, ([, w, d]) => `md:${w}-[${d / 7.68}vw]`],
  [/^mobile-([a-z]+)-(\d+)$/, ([, w, d]) => `${w}-[${d / 3.75}vw]`],
],

But,I want to have 4 media steps,I hope that `moble-x-x` is not default,like  [/^mobile-([a-z]+)-(\d+)$/, ([, w, d]) => `<md:${w}-[${d / 3.75}vw]`]
- [ ]  @media max-width:768px
- [ ] @media min-width:768px and max-width:1024px
- [ ] @media min-width:1024px and max-width:1280px
- [ ] @media min-width:1280px

**Comment by antfu** [comment]
TBH I personally do not enjoy the way Windi use those symbol to represent the difference. We have `lt-sm` to replace `<sm` in preset-uno, and yes we are lacking of `at-sm` so PR welcome :)
