### ISSUE TITLE
Using unocss on rollup

### ISSUE THREAD

**Issue by axmad386** [antfu/unocss#201]
Hi, Is unocss only work on vite only? I can't find how to use it with rollup, without vite. Thanks

**Comment by antfu** [comment]
I don't see it's common to use rollup to build a web app, can you share some examples?

**Comment by axmad386** [comment]
I build custom nodejs framework called lunox, you can see the example app here [here](https://github.com/kodepintar/lunox) and this is the framework [lunox](https://github.com/kodepintar/lunox-framework)
It using svelte as template engine. In development, I can use vite to render svelte component, unocss also work in this stage. But in production  build I cannot use vite, because of dynamic component. I ended up using rollup to compile all svelte component to  dist/server folder and render it from server.
The problem is, rollup cannot compile unocss

**Comment by axmad386** [comment]
I just want to confirm, if unocss only work with vite, I will close this issue. May be i have to change my production build to work with vite

**Comment by antfu** [comment]
Rollup itself does not handle CSS. UnoCSS would work in Vite is based on the fact that Vite has built-in supports for CSS. It's still possible to have UnoCSS working on Rollup, but I probably won't have enough experience and also motivation to do that, please feel free to experiment and maybe send a PR to us :) Thanks.

**Comment by axmad386** [comment]
Hi, thanks for answer. Finally I can make unocss work on production build. Like you said, rollup cannot handle css without additional plugin and I not expert on that. So, I switched my production build using vite with help of import.meta.glob. Hey it works :smiley:
