### ISSUE TITLE
Preset attributify: some attributes generate redundant CSS

### ISSUE THREAD

**Issue by UltraCakeBakery** [antfu/unocss#205]
Some elements have attributes that clash with the attributify preset.

For example: https://developer.mozilla.org/en-US/docs/Web/SVG/Attribute/fill

Out of the box the attributify preset generates redundant css for this attribute:

```svg
<circle cx="50" cy="50" r="40" stroke="green" stroke-width="4" fill="yellow" />
```
```css
[fill~="yellow"]{--un-fill-opacity:1;fill:rgba(250,204,21,var(--un-fill-opacity));}
```

Fortunately, the additional css doesn't break anything or cause any unexpected behavior. 
I do wonder however about how much css could be generated on pages with larger svgs.

Is this "problem" something Unocss or the attributify preset should take care of, or should my html parser not pass these attribute to the Unocss generator? Is there a recommended configuration to exclude attributes like these?

**Comment by antfu** [comment]
This is unfortunately the limitation for static analysis, we can't determine if an attribute is used to style or not. (Even without the attributify mode, there could still be some false positives on classes).

In v0.15, we introduced a new option `ignoreAttributes` for this, you can do:

```ts
presetAttributify({
  ignoreAttributes: ['fill']
})
```

And use the prefixed one when you want to use the Uno utilities:

```html
<div un-fill="yellow"/>
```
