### ISSUE TITLE
Attributify Mode - Align property calling text-align instead of align-content

### ISSUE THREAD

**Issue by MarioC3** [antfu/unocss#206]
Hello Guys!

When using Attributify mode, I noticed that when I call `align="center"` the class that gets applied is `text-align: -webkit-center` instead of `align-content: center`. 

```
<div w="full" h="full" flex justify="center" align="center">
    <p>Items go here</p>
 </div>
```

I'm not sure if this is a bug with uno or windi, just wanted to let you guys know here

**Comment by rafaelytakei** [comment]
Pretty sure both UnoCSS and WindiCSS inherit this from Tailwind, where the way to apply `align-content` is using `content-{alignment}`. [Docs](https://tailwindcss.com/docs/align-content)

**Comment by antfu** [comment]
See https://github.com/antfu/unocss/issues/205#issuecomment-985330309

**Comment by cfacundo** [comment]
`align="center"` is how we used to center things in tables back in the day, nowadays it's deprecated
https://developer.mozilla.org/en-US/docs/Web/API/HTMLTableElement/align
