### ISSUE TITLE
vscode extension crashing with presetIcons

### ISSUE THREAD

**Issue by mwohlan** [antfu/unocss#208]
First of all, thank you for this amazing project!! It makes so many things easier!

I just noticed, that the vscode extension crashes for me in my vue3 project, when using icons with the unocss (0.15.3) presetIcons

package.json
```json
"devDependencies": {
    "@iconify/json": "^1.1.438",
    "unocss": "^0.15.3",
  }
```

vite.config.js

```javascript   
Unocss({
        presets: [
          presetUno(),
          presetIcons({
            prefix: 'i-',
            extraProperties: {
              display: 'inline-block'
            }
          }),
          presetAttributify()
      ]
    })],
```

Every time I open a vue file with an icon from presetIcons (e.g. _i-iconoir-stats-report_ ) , the unocss extension crashes

**Comment by antfu** [comment]
Can you share the the error message in the VS Code devtools and provide a minimal repdouction? Thanks.

**Comment by mwohlan** [comment]
The best i could do for now: Install vitesse-lite according to your manual. Update all unocss dependencies to 0.15.3. Run pnpm i. Restart vscode if already started. Then this is the error I get when opening a vue file with an icon in it:
![Screenshot from 2021-12-03 16-01-55](https://user-images.githubusercontent.com/76627776/144624691-e632b275-e07f-4a98-8f98-0c9048054d88.png)

Seems to be an issue with preset-icons package. So maybe I should change the title :thinking:  With 0.14.2 ( so without updating to the newest unocss) there were no issues.
