### ISSUE TITLE
get color seems not work

### ISSUE THREAD

**Issue by fyeeme** [antfu/unocss#220]
version :0.1.5.4

those get function seems not work,as i cann't get `text-true-gray-500` work, also others get color not work too!.
![image](https://user-images.githubusercontent.com/6078758/144750005-3b88c38f-1961-4701-a753-25082d152c30.png)

![image](https://user-images.githubusercontent.com/6078758/144750039-17142dc8-c34c-4eb6-8839-fda6a4663d0f.png)

**Comment by fyeeme** [comment]
@chu121su12 , ths, all gets work well in color.ts except `blue-gray`

bg-blue-gray
text-blue-gray


example is here:

https://unocss.antfu.me/?html=DwEwlgbgBAFgtAMwK4BsVQC4FMAeG4DGWAdtgE5QIq5QDOW1B%2BxA9sVlAIZoBcGZnYrTAYwbOABYADFIB8AKChRQkKAFtOCpUpXRseOAFYc6BAHcAjDK7EwG7HABGLJMSJxuGG3c4OCL0jgwYgRgkQ5BHwcLWi1tJVcWAlpaRW1gAHpwCDidbKUCFE4UgF4AIn18FABzSjMAZms1CyhHaqcUJCw4aoEATzLc7QAVGA5g2gxBL3EQLA1iECgAQQwWNTACKABhAGVdqBJq4KwAOjSdLMgh5XzMXCra80apdRa2whYWFB7%2BoxkblBRuMhFNSFBZvNBEtVutNjt9odiMd2Od4plskNdEpKnAanUXm9Wu0zJwyGpfpw%2Bv85BcRmMoBMwTNiHA5gsYWsNls9gcjic0ekrjk6bdVPcDPjnk13u1%2BF1KdTDADRUCGUzphDWezoSsufDeUiUWc6Rjrqb8moAEyUag4KAAKyQkzACGpRFIWAouKtJghAAdGrAWBAveUWP6ABxSQaq4CcVVKMCEMnOVkoFjVFg9EQwJCORMS-DBMZkESFmBkLAIcowDAYf20HgZDLHDB5xynfxqDLTZAZRLJWhlQtTMjVLAYcoAfUcRWIAGsR-ElLJMppTcK4maRTuFNjOI5aN8kNhWix6%2BsjFAy9U63BXtQEPhXriPeQA0HpbSlJCOVAAHbGVBTUgOQNA%2BigAhnX1AAvQ9qHkPcgA&config=JYWwDg9gTgLgBAbzgEwKYDNgDtUGEJaYDmcAvnOlBCHAOQCuWEAxgM6u0BQnqAHpLBQYAhvQA28NJhz5CwIgAoEnOHCjjUrAFxwA2itV7azeqxjUAtOrGpaAGkRxmEMdB20oqZLTIBdA-6kAJRAA&options=N4IgzgLgTglgxhEAuaBXApgXyA

**Comment by chu121su12** [comment]
Previously `blue` take priority over `blue-something`. More fix in https://github.com/antfu/unocss/commit/2c78f17374156ff365caa53dea598713f6465119.
Thank you for the feedback
