### ISSUE TITLE
Test snapshot maybe linked?

### ISSUE THREAD

**Issue by chu121su12** [antfu/unocss#226]
PR #225 cannot pass test without updating the other unrelated test suite (https://github.com/antfu/unocss/pull/225/commits/fe69eadced0ca2963b26cd507075575dd6ade4a6).

**Comment by antfu** [comment]
It

**Comment by chu121su12** [comment]
Updated #255. Still fails with the original tests, even when duplicating the whole handlers.ts.

**Comment by chu121su12** [comment]
preset-uno is alias of preset-wind
https://github.com/antfu/unocss/blob/22eb37fb214fa05b4e85c65416585d6ca49a383e/packages/preset-uno/src/index.ts#L10
