### ISSUE TITLE
Astro@next compatibility

### ISSUE THREAD

**Issue by lakano** [antfu/unocss#24]
Hi !

Amazing works, congrats! :-)

Since Astro.build have switched to Vite, I'm trying to use your tool with Astro, but it doesn't seems to works, I receive error 404 to fetch the file /@unocss-entry-css

Here the steps I've done:
```
npm init astro next-starter -- --template snowpackjs/astro/examples/starter#next
cd next-starter
npm install astro@next
npm install
npm i -D unocss

```
edit /astro.config.js like this:
```
import Unocss from 'unocss/vite'
import { presetUno, presetAttributify } from 'unocss'

export default (
  {
    vite: {
      plugins: [
        Unocss({
          presets: [
            presetAttributify({ /* preset options */}),
            presetUno(),
            // ...custom presets
          ]    
        }),
      ],
    },

  }
);
```
BTW, in your documentation there is this line:
« import { presetUno, presetAttributify, presetWind } from 'unocss' » 
But « presetWind » doesn't works, I suppose this was a separate package before and now merged in the default presetUno ? ( I don't see @unocss/preset-windi » on npmjs.com )

Replace the content of ./src/pages/index.astro with:
```
---
import 'uno.css' 
---
<html>
<body>
    <span class="text-red-500">Text</span>
</body>
</html>
```

And:
`npm run dev`

Open http://localhost:3000 to see the error, and the « Text » is not red.

Thank you in advance for your help !

**Comment by lakano** [comment]
Sorry @antfu but this patch haven't fixed the problem :(
I've done the same example, the installed package is 0.4.7

In my developer console I still have:
`18:54 [astro] 404 /@unocss-entry.css                       0ms`

May be it's more a bug related to Astro.build, I'll try to find if they have a solution too.

**Comment by hans-d** [comment]
Seems to be working now 
```
"devDependencies": {
    "astro": "^0.21.0-next.1",
    "unocss": "^0.6.6"
  }
```
https://stackblitz.com/edit/github-d4rp6r?file=src/pages/index.astro

**Comment by electroheadfx** [comment]
> Seems to be working now
> 
> ```
> "devDependencies": {
>     "astro": "^0.21.0-next.1",
>     "unocss": "^0.6.6"
>   }
> ```
> 
> https://stackblitz.com/edit/github-d4rp6r?file=src/pages/index.astro

From me the project doesn't work (from stackblitz.com) and in local the style doesn't update, only from fresh server restart
