### ISSUE TITLE
before pseudo-element not selected by translate-[xy]-full

### ISSUE THREAD

**Issue by SIGUSR97** [antfu/unocss#240]
![image](https://user-images.githubusercontent.com/52692296/145239801-74e5bf22-29a8-4ca4-ade2-5366915dd571.png)

Apparently the first generate CSS selector does not select the before pseudo-element, making this rule pretty much ineffective. I have not tested this with other rules, but it might occur elsewhere.

**Comment by antfu** [comment]
This is the expected behavior. The first class is the transform base, which makes able to use translate without having a `transform` class alongside. When you have multiple transform applied, you will see the base rule will be merged.

**Comment by SIGUSR97** [comment]
> This is the expected behavior. The first class is the transform base, which makes able to use translate without having a `transform` class alongside. When you have multiple transform applied, you will see the base rule will be merged.

I see how this transform base works, but my goal is to transform the `::before` pseudo-element, not its parent. The selectors above will only select the `div` element but not the `::before` pseudo-element.

**Comment by antfu** [comment]
Oh I see, yes this is a bug. We should treat before/after differently than hover/active.

**Comment by chu121su12** [comment]
Closed in https://github.com/antfu/unocss/commit/750594e25175aadc547907de141cb7987c228e22
