### ISSUE TITLE
animate-pulse is scaling the object

### ISSUE THREAD

**Issue by vipero07** [antfu/unocss#241]
The pulse keyframes are wrong and do not align with windicss or tailwind.
Instead of pulsing opacity it pulses scale.

**Comment by userquin** [comment]
From [windicss pulse keyframes](https://github.com/windicss/plugins/blob/main/packages/animations/animate/keyframes/keyframes.js), it uses scale not opacity:
```ts
const keyframePulse = {
    'from': {
        transform: 'scale3d(1, 1, 1)'
    },
    '50%': {
        transform: 'scale3d(1.05, 1.05, 1.05)'
    },
    'to': {
        transform: 'scale3d(1, 1, 1)'
    }
};
```

**Comment by userquin** [comment]
here we have it on `preset-wind`:
```ts
// src/packages/preset-wind/src/rules/animation.ts
// https://windicss.org/plugins/community/animations.html
const keyframes: Record<string, string> = {
  'spin': '{from{transform:rotate(0deg)}to{transform:rotate(360deg)}}',
  'ping': '{0%{transform:scale(1);opacity:1}75%,100%{transform:scale(2);opacity:0}}',
  'bounce': '{from,20%,53%,80%,to{animation-timing-function:cubic-bezier(0.215,0.61,0.355,1);transform:translate3d(0,0,0)}40%,43%{animation-timing-function:cubic-bezier(0.755,0.05,0.855,0.06);transform:translate3d(0,-30px,0)}70%{animation-timing-function:cubic-bezier(0.755,0.05,0.855,0.06);transform:translate3d(0,-15px,0)}90%{transform:translate3d(0,-4px,0)}}',
  'flash': '{from,50%,to{opacity:1}25%,75%{opacity:0}}',
  'pulse': '{from{transform:scale3d(1,1,1)}50%{transform:scale3d(1.05,1.05,1.05)}to{transform:scale3d(1,1,1)}}',
...
```

**Comment by userquin** [comment]
the problem is that `tailwind` uses scale, see it here: https://tailwindcss.com/docs/animation

```css
/* animate-pulse */
animation: pulse 2s cubic-bezier(0.4, 0, 0.6, 1) infinite;

@keyframes pulse {
  0%, 100% {
    opacity: 1;
  }
  50% {
    opacity: .5;
  }
}
```

**Comment by userquin** [comment]
@antfu should we add also the tailwind animations? Since `preset-wind` is including both, we could add the tw, maybe with some suffix/prefix (using for default animate windi version)?

/cc @vipero07

**Comment by userquin** [comment]
I'll add `tw-pulse` and `tw-bounce`, `spin` and `ping` already exists, PR in a few minutes...

**Comment by chris-zhu** [comment]
I also found this problem in https://github.com/antfu/unocss/pull/177, I'm sorry I didn't handle the compatibility @userquin

**Comment by userquin** [comment]
@chris-zhu no problem, when I add the animate module we decide to use windi ones, originally there was only tailwind ones.

**Comment by userquin** [comment]
@chris-zhu I should add these defaults no? 

```css
animation: pulse 2s cubic-bezier(0.4, 0, 0.6, 1) infinite;
```

that is:

```ts
const durations: Record<string, string> = {
  'tw-pulse': '2s', // <== THIS ENTRY
  'heart-beat': '1.3s',
  'bounce-in': '0.75s',
  'bounce-out': '0.75s',
  'flip-out-x': '0.75s',
  'flip-out-y': '0.75s',
  'hinge': '2s',
}

const timingFns: Record<string, string> = {
  'tw-pulse': 'cubic-bezier(0.4,0,.6,1)', // <== THIS ENTRY
  'head-shake': 'ease-in-out',
  'heart-beat': 'ease-in-out',
  'pulse': 'ease-in-out',
  'light-speed-in-left': 'ease-out',
  'light-speed-in-right': 'ease-out',
  'light-speed-out-left': 'ease-in',
  'light-speed-out-right': 'ease-in',
}
```

**Comment by userquin** [comment]
Also for `ping`, the timing should be `cubic-bezier(0,0,.2,1)`

**Comment by chris-zhu** [comment]
> @chris-zhu I should add these defaults, no?
> 
> ```css
> animation: pulse 2s cubic-bezier(0.4, 0, 0.6, 1) infinite;
> ```
> 
> that is:
> 
> ```ts
> const durations: Record<string, string> = {
>   'tw-pulse': '2s', // <== THIS ENTRY
>   'heart-beat': '1.3s',
>   'bounce-in': '0.75s',
>   'bounce-out': '0.75s',
>   'flip-out-x': '0.75s',
>   'flip-out-y': '0.75s',
>   'hinge': '2s',
> }
> 
> const timingFns: Record<string, string> = {
>   'tw-pulse': 'cubic-bezier(0.4,0,.6,1)', // <== THIS ENTRY
>   'head-shake': 'ease-in-out',
>   'heart-beat': 'ease-in-out',
>   'pulse': 'ease-in-out',
>   'light-speed-in-left': 'ease-out',
>   'light-speed-in-right': 'ease-out',
>   'light-speed-out-left': 'ease-in',
>   'light-speed-out-right': 'ease-in',
> }
> ```

yes. and thank you for correcting my mistakes, I will check strictly next time.

**Comment by userquin** [comment]
@chris-zhu no problem, too many things, I will update it again to use alternate for this 2 guys: `pulse`  and `bounce`
