### ISSUE TITLE
UnoCSS Renders `?` Key CSS When Using Ternary

### ISSUE THREAD

**Issue by tuhanayim** [antfu/unocss#258]
I'm using UnoCSS with Vue 3 Script Setup Sugar but even though I'm not using `?` key, UnoCSS and UnoCSS VSCode plugin detects ternary's question mark as a key and renders it. The presets I use are `presetUno` and `presetIcons`. I don't use `attributify` mode.
## My Code (<script setup>)
![image](https://user-images.githubusercontent.com/83988414/145683898-3d4661ba-981b-4e06-a826-73b9c3ecf810.png)
## Built CSS (formatted)
![image](https://user-images.githubusercontent.com/83988414/145683912-3525886f-e8fd-470c-ab58-9c6fb08863b6.png)

**Comment by userquin** [comment]
@tuhanayim this should be only on dev mode, we can modify the rule to be more strict

**Comment by tuhanayim** [comment]
@userquin no, the screenshot of built CSS is production build. And exists on my sites bundled CSS file too.

https://tuhana.me/assets/index.3df2093a.css
![image](https://user-images.githubusercontent.com/83988414/145685303-16a41e48-e3dc-4d18-aa6b-336f6fb21920.png)

**Comment by userquin** [comment]
do you make the build with dev mode `devMode: 'dev'`?

**Comment by userquin** [comment]
@tuhanayim https://github.com/antfu/unocss/blob/main/packages/preset-mini/src/rules/question-mark.ts#L11

**Comment by tuhanayim** [comment]
But i don't use `envMode: 'dev'`. And its default value is `build`.
## vite.config.ts
![image](https://user-images.githubusercontent.com/83988414/145685528-90f28a3c-ab88-4454-9139-d22ae82da5d4.png)

**Comment by userquin** [comment]
@tuhanayim just asking you... I'm checking it right now

**Comment by userquin** [comment]
@tuhanayim confirmed, it is a regresion, we remove the dev rules and the default `envMode` is initialized for `HMR` and `context` to `dev`.

@antfu for context, we force to `envMode = 'dev' ` here https://github.com/antfu/unocss/blob/main/packages/vite/src/config-hmr.ts#L12 and here https://github.com/antfu/unocss/blob/main/packages/plugins-common/context.ts#L45 and on docs the default is `build`.

Maybe just change the rule to use `process.env.NODE_ENV` or adding another internal `devRules` entry?

**Comment by userquin** [comment]
@tuhanayim it should be fixed for build but on dev there is no way to bypass it. For example we cannot bypass this type of expressions: `const x = y ? 'x' : 'y'`, we should analize the code to check if inside an script or jsx, so will not be fixed on dev mode. The PR fix the build exclusion only if `envMode`  not configured or using `build`.
