### ISSUE TITLE
[feature] [core] Synchronous version of the generate function

### ISSUE THREAD

**Issue by alexanderniebuhr** [antfu/unocss#26]
@antfu Not investigated this in detail yet, but I was wondering, if it is possible to get a synchronous API for the `.generate()` function, since it would be great to have it as an option?

https://github.com/antfu/unocss/blob/main/packages/core/src/generator/index.ts#L40-L44

**Comment by antfu** [comment]
I think it makes more sense to have your usage supports async functions instead, otherwise, we are basically saying we are limiting the possibilities and potential perf here to have asynchronous API. Sorry as I would not expect it to happen in the near future.

**Comment by shellscape** [comment]
This is disappointing. It was a bummer that `shikiji` had no sync API, and now `unocss`. This is really limiting the scenarios in which this can be used.
