### ISSUE TITLE
No output for translate-x-[var(--page-translate-x)]

### ISSUE THREAD

**Issue by sondh0127** [antfu/unocss#262]
![image](https://user-images.githubusercontent.com/62163604/145708283-43bb52f2-0e79-450a-b2ca-34805605bfed.png)
![image](https://user-images.githubusercontent.com/62163604/145708290-fe5ccaae-8063-4394-8173-9687e13afdaa.png)

https://unocss.antfu.me/?html=DwEwlgbgBAxgNgQwM5ILwCIAuAnBA7JRTAUwFoAPUgbQgWwApTSAHBAczJ30IRIoEoAuugB8AKChQAKrgIAzAPbYAtlDnYFqgMIBlHVABqdMcAD04CCKA&config=JYWwDg9gTgLgBAbzgEwKYDNgDtUGEJaYDmcAvnOlBCHAOQCuWEAxgM6u0BQnqAHpLBQYAhvQA28NJhz5CwIgAoEnOHCjjUrAFxwA2itV7azeqxjUAtOrGpaAGkRxmEMdB20oqZLTIBdA-6kAJRAA&options=N4IgzgLgTglgxhEAuaBXApgXyA

**Comment by chu121su12** [comment]
Closed in https://github.com/antfu/unocss/commit/0d1f5c5b8184baea47fc5695eb1ff89645290408
