### ISSUE TITLE
`border-b` outputs nothing

### ISSUE THREAD

**Issue by QiroNT** [antfu/unocss#264]
repl: https://unocss.antfu.me/?html=DwEwlgbgBAxgNgQwM5ILwCIBGB7ATiAU1wFpN0A%2BYAenAnKA

And tests got ignored.

https://github.com/antfu/unocss/commit/5f3e85e83a05660852722ce834b5c816ae57e190#diff-295449f76c15fc2b4bb9c10d693949b3dae7744b2eca1eab42b4a2d43947cd79L21

![](https://user-images.githubusercontent.com/31543482/145712760-785726c8-2a55-4771-8da6-474ec2c5ad95.png)

**Comment by userquin** [comment]
@chu121su12 regresion for defaults?
