### ISSUE TITLE
Cannot read properties of undefined (reading '__nuxt_plugin')

### ISSUE THREAD

**Issue by productdevbook** [antfu/unocss#27]
branch: unocss
https://github.com/productdevbook/productdevbook.com/tree/unocss

<img width="985" alt="CleanShot 2021-11-01 at 06 43 34@2x" src="https://user-images.githubusercontent.com/38668796/139618835-608f3226-9139-46cb-b1af-66e51d723177.png">

**Comment by productdevbook** [comment]
hi antfu, iam update fixed, but dont change color and dont hot reload

**Comment by productdevbook** [comment]
<img width="861" alt="CleanShot 2021-11-02 at 13 43 43@2x" src="https://user-images.githubusercontent.com/38668796/139832288-a60a6a3c-89a3-42a7-ae40-3fe46d666713.png">

**Comment by productdevbook** [comment]
hmm, is fixed :D , thats true ? 
![CleanShot 2021-11-02 at 13 45 31](https://user-images.githubusercontent.com/38668796/139832510-36d84183-fed6-4261-810a-e59d3d49a304.png)

**Comment by productdevbook** [comment]
iam remove windicss but, dont color change. Does windicss have to be installed ? 
<img width="646" alt="CleanShot 2021-11-02 at 13 48 30@2x" src="https://user-images.githubusercontent.com/38668796/139832968-1b59eaf5-fba0-4177-a436-2a2bbad13972.png">

**Comment by antfu** [comment]
This is a bug of Nuxt SSR, I am working on it.

**Comment by antfu** [comment]
You can now use `@unocss/nuxt` for that. (the FOUC is still in progress)
