### ISSUE TITLE
include files that are not transform by vite plugin

### ISSUE THREAD

**Issue by SIGUSR97** [antfu/unocss#280]
## Usecase

I have an Elm project that I want to use unocss with. By the nature of using a different languague, only the entry file `Main.elm` is imported by the project's `main.ts` file. While the rest of the project's imports are handle by `vite-plugin-elm` and transpiled to js, therefore not included by unocss. I understand that I can use the unocss cli to generate css for my project. But appearently the inspector only comes with the vite plugin and I'd really like to use it.

**Comment by antfu** [comment]
PR welcome to add `.elm` here https://github.com/antfu/unocss/blob/8c277dee9f411f6325332ccccbba6d1ddc16ac54/packages/plugins-common/defaults.ts#L2

Thanks

**Comment by userquin** [comment]
@SIGUSR97 just add `elm` extension on `include` option, I have it working on local (https://imgur.com/CDE82OG).

I can include `elm` if you don't want to make a PR.

```ts
import { defineConfig } from "vite";
import elmPlugin from "vite-plugin-elm";
import UnoCSS from 'unocss/vite'
import { presetUno } from "@unocss/preset-uno";
import presetIcons  from "@unocss/preset-icons";

export default defineConfig({
  plugins: [
    elmPlugin(),
    UnoCSS({
      include: [/\.elm$/],
      shortcuts: [
        { logo: 'i-logos-elm w-6em h-6em transform transition-800 hover:rotate-360' },
      ],
      presets: [
        presetUno(),
        presetIcons()
      ],
    })
  ],
});
```

**Comment by userquin** [comment]
I have created a repo here https://github.com/userquin/vite-unocss-elm, created from this template https://github.com/lindsaykwardell/vite-elm-template

**Comment by SIGUSR97** [comment]
@userquin Thanks for your assistance! I felt reluctant to make a PR to this repo since I did stray away from my last project to work on something else, and I wasn't sure if adding another default import was what I wanted as a general solution. I tested your repo and things seem to work out fine! Except with the inspector, for some reason, it's not showing the included elm files (HelloWorld.elm) and the contents in the files. Not really sure if this is a problem with the inspector or with elm projects specifically.
![image](https://user-images.githubusercontent.com/52692296/147623667-9fbe5848-b58f-40d5-ad90-597e2d886508.png)

**Comment by userquin** [comment]
The extra dependency was for testing purposes, you only need the check the vite config file. On the repo I have removed the inspect plugin.

**Comment by userquin** [comment]
@SIGUSR97 update to latest version unocss `0.21.0` to see source on inspector, I need to add `elm` to codemirror on it: I also update the template here https://github.com/userquin/vite-unocss-elm

![imagen](https://user-images.githubusercontent.com/6311119/148137633-7e12b497-076d-453e-a339-174317277e5f.png)

**Comment by userquin** [comment]
@SIGUSR97 to see the elm source just configure the elm plugin after unocss plugin, updated also my template:

![imagen](https://user-images.githubusercontent.com/6311119/148138000-6b447cbb-6671-4ca9-b74f-a58ee200b0bd.png)
