### ISSUE TITLE
Unocss Icons do not show when added to an element through dynamic class bindings

### ISSUE THREAD

**Issue by REDEAKAA** [antfu/unocss#282]
When using unocss icons presets, the icons show up when I use then via the attributify means, and when I implicitly specify them using classes. But they do not show up when I loop through an array of elements, while binding the icon names dynamically to an element. Note that this issue only happens when I'm fetching the array of icon names from an external store(pinia).

I also noticed that they then show up when I manually put the icons one by one by either means, but once I rerun my dev server, they disappear. And this happens with any icon set.

```js
const navLinks = [
	{
		label: "Dashboard",
		path: "/",
		icon: "i-bx-bxs-dashboard text-red-500"
	},
	{
		label: "Workspace",
		path: "/workspace",
		icon: "i-bx-bx-buildings text-green-500"
	},
	{
		label: "Categories",
		path: "/categories",
		icon: "i-bx-bx-category text-yellow-500"
	}
]
```

```vue
<ul class="relative w-full p-1 font-semibold">
	  <li class="w-full" v-for="(item, index) in navLinks" :key="index">
		  <NuxtLink :to="item.path" class="flex w-full" hover="bg-base-100">
			  <span class="min-w-45px h-40px flex-center">
				  <div :class="item.icon" />
			  </span>
			  <span class="pl-2 h-40px text-xs flex whitespace-nowrap items-center pr-5">{{ item.label }}</span>
		  </NuxtLink>
	  </li>
</ul>
```

**Comment by antfu** [comment]
Probably this? https://github.com/antfu/unocss#scanning

**Comment by REDEAKAA** [comment]
Nah! so I noticed that same issue happens with even color utilities, so my guess is that dynamic classes applied using the v-bind directive(:class="") are not being processed by unocss.

`

**Comment by antfu** [comment]
Can you share a minimal reproduction? Thanks.

**Comment by REDEAKAA** [comment]
Sorry for the late reply.

I hope this remake helps out

```vue
<script setup lang="ts">
const myButtons = [
	{
		icon: "i-uil-notebooks",
		label: "Notebooks"
	},
	{
		icon: "i-uil-bookmarks",
		label: "Bookmarks"
	}
]
</script>

<template>
	<div>
		<SomeButton
			v-for="(item, index) in myButtons"
			:key="index"
			class="px-3 py-2 text-light-300 bg-red-500 text-sm"
		>
			<div :class="item.icon" />
			{{ item.label }}
		</SomeButton>
	</div>
</template>
```

**Comment by antfu** [comment]
It should work. Can you share a repo with your config and setup?

**Comment by REDEAKAA** [comment]
Uhm! I haven't really faced the issue again, who knows, maybe it's just another case of paranormal activities happening 😲. Thanks for the response though, I promise to let you know if I encounter same or similar bugs in future. Thanks for such an awesome tool @antfu  😊,

**Comment by PMLS3** [comment]
@therealokoro How did you fix this? Mine is giving me the exact same problem through dynamic bindings.... I'm using nuxt3

**Comment by PMLS3** [comment]
> @therealokoro How did you fix this? Mine is giving me the exact same problem through dynamic bindings.... I'm using nuxt3

okay, seems it works but only on some of material design icons... @antfu is there a setting that I might be missing to include all icons?

in nuxt config: 
 unocss: {

    uno: true,
    icons: true
    attributify: true,

**Comment by sadeghbarati** [comment]
@PMLS3 

it's because your svgs icons have problem and unocss-preset-icon can't recognize svg errors,
 use [svgo](https://jakearchibald.github.io/svgomg/) before add to unocss preset
 
 or use this config in vite with `@iconify/tools`
 
 
 ```js
 import { defineConfig } from 'vite'
import vue from '@vitejs/plugin-vue'

import unocss from 'unocss/vite'
import presetUnocss from '@unocss/preset-uno'
import presetIcon from '@unocss/preset-icons'
import presetAttributify from '@unocss/preset-attributify'

import Inspect from 'vite-plugin-inspect'

import { FileSystemIconLoader } from '@iconify/utils/lib/loader/node-loaders'


import {
  importDirectory,
  parseColors,
  runSVGO,
  deOptimisePaths,

} from '@iconify/tools'

// https://vitejs.dev/config/
export default defineConfig({
  plugins: [
    unocss({

      presets: [
        presetUnocss(),
        presetIcon({
          autoInstall: false,
          prefix: 'i-',

          collections: {
            'test': FileSystemIconLoader('./icons'),
            'custom-svg': async () => {
              // Load icons
              const iconSet = await importDirectory('./icons');

              // Clean up each icon
              await iconSet.forEach(async (name) => {
                const svg = iconSet.toSVG(name);

                // Change color to `currentColor`
                // Optimise
                await runSVGO(svg);

                // Update paths for compatibility with old software
                await deOptimisePaths(svg);

                // Update icon in icon set
                iconSet.fromSVG(name, svg);
              });

              // Export as IconifyJSON
              return iconSet.export();
            },
          }
        }),
        presetAttributify()
      ]
    }),

    vue(),

    Inspect()
  ]
})

 ```

**Comment by green-anger** [comment]
I used an array of icons in a pinia store and then v-for in .vue where it was imported, similar to @therealokoro 's initial post. The issue was resolved by adding `// @unocss-include` to the store .ts file - [source](https://unocss.dev/guide/extracting#extracting). Make sure to use full icon names as mentioned before. Example:

```ts
// @unocss-include
export const useMenus = defineStore('menus', {
  state: (): State => {
    return {
      menus: [
        { icon: 'i-carbon:home', title: 'Home', to: '/' },
        { icon: 'i-carbon:information', title: 'About', to: '/about' },
      ],
    };
  },
});
```

**Comment by clopezpro** [comment]
> 

It is my case, the icons do not appear when I use :class
![image](https://github.com/unocss/unocss/assets/27446663/50700a51-86e8-43e9-831d-96127c01ef6c)

**Comment by clopezpro** [comment]
> ```ts
> // @unocss-include
> export const useMenus = defineStore('menus', {
>   state: (): State => {
>     return {
>     
> ```

https://github.com/clopezpro/myERP

**Comment by clopezpro** [comment]
> 

https://github.com/clopezpro/myERP

**Comment by provabeer** [comment]
Hello! Considering i have an array inside a json file (nuxt content). hw

> I used an array of icons in a pinia store and then v-for in .vue where it was imported, similar to @therealokoro 's initial post. The issue was resolved by adding `// @unocss-include` to the store .ts file - [source](https://unocss.dev/guide/extracting#extracting). Make sure to use full icon names as mentioned before. Example:
> 
> ```ts
> // @unocss-include
> export const useMenus = defineStore('menus', {
>   state: (): State => {
>     return {
>       menus: [
>         { icon: 'i-carbon:home', title: 'Home', to: '/' },
>         { icon: 'i-carbon:information', title: 'About', to: '/about' },
>       ],
>     };
>   },
> });
> ```

hello. how can i use this solution (// @unocss-include) considering my array with custom icons is inside a json file?

ex.

  "testIcons": [
    {
      "icon": "i-custom:house",
      "text": "Some text"
    },

**Comment by therealokoro** [comment]
From the docs, there are two ways you could have unocss scan your json files

1. Build tool pipelines ([Read Here](https://unocss.dev/guide/extracting#extracting-from-build-tools-pipeline))
```ts
// uno.config.ts
export default defineConfig({
  content: {
    pipeline: {
      include: [
        // include your files here
        'src/**/*.{json}', // this will look files 
        'src/path-to-file/icons-list.json' // or you could be more specific
      ]
    }
  }
})
```

2. Extracting from file system ([Read Here](https://unocss.dev/guide/extracting#extracting-from-filesystem))
```ts
// uno.config.ts
export default defineConfig({
  content: {
    filesystem: [
      // include your files here
      'src/**/*.{json}', // this will look files 
      'src/path-to-file/icons-list.json' // or you could be more specific
    ]
  }
})
```

Give it a try.
