### ISSUE TITLE
how do some icons add safelist ? 

### ISSUE THREAD

**Issue by productdevbook** [antfu/unocss#283]
According to the result from the API, I need to show the icons, but it does not show because they are not added before. It would be great if we could write safelist like in Tailwindcss.

**Comment by antfu** [comment]
We have a safelist option don't we?

**Comment by productdevbook** [comment]
https://github.com/antfu/unocss/tree/main/packages/preset-icons

I'm talking about adding the icons to the safelist.

**Comment by antfu** [comment]
https://github.com/antfu/unocss/blob/8c277dee9f411f6325332ccccbba6d1ddc16ac54/packages/core/src/types.ts#L155-L158

the functionality is provided by core and works on any presets.
