### ISSUE TITLE
gradient="to-r from-yellow-400 via-red-500 to-pink-500"  none-effect

### ISSUE THREAD

**Issue by 729902288** [antfu/unocss#288]

**Comment by chu121su12** [comment]
The syntax is 
```bg-gradient-to-r from-yellow-400 via-red-500 to-pink-500```

https://unocss.antfu.me/?html=DwEwlgbgBALgpgDxgWgKwIDa0SgxnAO3gCcoAHAFnICMAOAKCiaeoHNlXiBDcQlGAPbJSAM2ICAtsgCecDBgEB3ZBQAMqqBDBdhcEGnWwhZMAQDWB1fQB8jKAFcCA3AGcX9YAHpwEW0A

**Comment by antfu** [comment]
I think it makes sense to support the optional prefix for `from`, `via`, `to` to make this usage works. Just like how we did with `flex="gap-2"` and `grid="gap-2"`
