### ISSUE TITLE
Color opacity not working on attributify mode

### ISSUE THREAD

**Issue by zirbest** [antfu/unocss#296]
### color opacity: `Attributify Mode`
not working

```html
<div ... bg-blue/22 border-red/30></div>
```
until

```html
<div ... class="bg-blue/22 border-red/30"></div>
```

[demo](https://unocss.antfu.me/?html=DwEwlgbgBAFgtAMwK4BsVQSgpgDygKyQGcAXMBATzgGMsA7ErAJyjEYFsib7GWBzAIYAHOACYAfACgoUUJCgiAjABYoAIwD2TEM3VadTOEywgA9AGYADFHHBT4CFJlzoS1Zu27qKAUSIBeACIPAyMTC0tA23tIJ1kHBTgVdT44NRQkLFNRCTsHOJdE5O9fAODU9Mzs0Si82Mk6xyA&config=JYWwDg9gTgLgBAbzgEwKYDNgDtUGEJaYDmcAvnOlBCHAOQCuWEAxgM6u0BQnqAHpLBQYAhvQA28NJhz5CwIgAoEnOHCjjUrAFxwA2itV7azeqxjUAtOrGpaAGkRxmEMdB20oqZLTIBdA-6kAJRAA&options=N4IgzgLgTglgxhEAuaBXApgXyA)

**Comment by userquin** [comment]
@zirbest use `bg-blue op-22`, I think you cannot use `/` on attr mode.

**Comment by antfu** [comment]
We support `:` for attributify mode
`<div ... bg-blue:22 border-red:30></div>`

**Comment by zirbest** [comment]
> @zirbest use `bg-blue op-22`, I think you cannot use `/` on attr mode.

@userquin did you mean 
```html
<div .. bg-red bg-op-20>
```
this is what i'm looking for `:`

> We support `:` for attributify mode `<div ... bg-blue:22 border-red:30></div>`

**Comment by userquin** [comment]
both works: `bg-blue:22` and `bg-blue op-22`
