### ISSUE TITLE
Shadow color not affect

### ISSUE THREAD

**Issue by zirbest** [antfu/unocss#297]
### Shadow color

```html
<div h-full flex justify-center items-center gap-2>
  <div p-14 shadow-lg shadow-red></div> <!-- working -->
  <div p-14 shadow-xl shadow-red></div> <!-- not working -->
</div>
```

Maybe a problem with the order ? 

[demo](https://unocss.antfu.me/?html=DwEwlgbgBAFgtAMwK4BsVQSgpgDygKyQGcAXMBATzgGMsA7ErAJyjEYFsib7GWBzAIYAHOACYAfACgoUUJCgiAjABYoRGAJAB7AO5wUfNRu16mWEOOAB6cBCky50JavWbdcHOlcm4Zi9dspAMhxIA&config=JYWwDg9gTgLgBAbzgEwKYDNgDtUGEJaYDmcAvnOlBCHAOQCuWEAxgM6u0BQnqAHpLBQYAhvQA28NJhz5CwIgAoEnOHCjjUrAFxwA2itV7azeqxjUAtOrGpaAGkRxmEMdB20oqZLTIBdA-6kAJRAA&options=N4IgzgLgTglgxhEAuaBXApgXyA)

**Comment by userquin** [comment]
@zirbest have you a monitor with xl resolution? the shadow is only applied when you have the window on xl, so the style shadow-red is only applied when shadow-xl match.

**Comment by userquin** [comment]
this seems to be bug

**Comment by userquin** [comment]
we should change the order of the shadow-<breakpoint>:

![imagen](https://user-images.githubusercontent.com/6311119/147150453-593e14d2-0cc1-4061-b859-7481be0d84b2.png)

**Comment by zirbest** [comment]
this is the right order 

```css
[shadow-lg=""]{...}
[shadow-xl=""]{...}
[shadow-red=""]{...}
```

**Comment by userquin** [comment]
maybe we can fix it using another approach: `{--unshadow-color: var(--un-shadow-color, 0,0,0)}` instead declaring it:

![imagen](https://user-images.githubusercontent.com/6311119/147152058-24d29706-b113-4d8a-8d7b-5abbddbc5b7e.png)
