### ISSUE TITLE
Build issue when using vite@2.5.x, but vite@2.6.x works fine 

### ISSUE THREAD

**Issue by guygubaby** [antfu/unocss#30]
# Build issue when using `vite@2.5.x` 

## Description 

Only get [PLACEHOLDER](https://github.com/antfu/unocss/blob/3495a6e76fc8025f73e85604a45eaa615f48927e/packages/vite/src/modes/global/shared.ts#L10) in output css assets after build

## Env

1. `vite@2.5.0`
2. production mode (`vite build`)

## Demo repository

The playground demo can be find [here](https://github.com/guygubaby/unocss-playground). And the [css bundle](https://github.com/guygubaby/unocss-playground/blob/0dc26a83bc7bf3bfc1e160c183b4d84eb5d11b13/dist/assets/index.222c9abe.css?_pjax=%23js-repo-pjax-container%2C%20div%5Bitemtype%3D%22http%3A%2F%2Fschema.org%2FSoftwareSourceCode%22%5D%20main%2C%20%5Bdata-pjax-container%5D#L1)

**Comment by antfu** [comment]
Any blockers for you to upgrade Vite to 2.6.x?
