### ISSUE TITLE
problem shadow-2xl & shadow-inner

### ISSUE THREAD

**Issue by zirbest** [antfu/unocss#310]
`shadow-2xl` not affect 

```html
<!--  shadow-2xl not affect -->
<div h-25% flex justify-center items-center gap-2>
  <div p-14 border b-gray-1 shadow-sm ></div>
  <div p-14 border b-gray-1 shadow ></div>
  <div p-14 border b-gray-1 shadow-lg ></div>
  <div p-14 border b-gray-1 shadow-xl ></div>
  <div p-14 border b-gray-1 shadow-2xl></div> <!-- here -->
</div>
```
---
`shadow-inner` not affect 
```html
<!--  shadow-inner not affect -->
<div h-25% flex justify-center items-center gap-2>
  <div p-14 border b-gray-1 shadow-inner shadow-sm ></div>
  <div p-14 border b-gray-1 shadow-inner shadow ></div>
  <div p-14 border b-gray-1 shadow-inner shadow-lg ></div>
  <div p-14 border b-gray-1 shadow-inner shadow-xl ></div>
  <div p-14 border b-gray-1 shadow-inner shadow-2xl></div> <!-- only here -->
</div>
```
[REPL](https://unocss.antfu.me/?html=DwQgtGAEkM4BYEMAmB7A7mATADwDaQDsUAXSBAM3IFMBjUiAPgChgkBLAN0jiwFYBSSOVxVskAFYBXGMTbkAnmBpUCxKgCdIbNQFsYSlWs0BzBAAcszaK06QLARgAskAEYp1SDa7DH1CRfawiKgYMDqQDMAA9OwcVpA2XA7Obh5eLj5%2BAUHI6BHRsfGJdmBOru6emhm%2B-qU5IWC4xvkxnEWxJWWpld412fC5GHgthUzWHcnlaVWZtYEDDTi4ka1xCeBQcBpUkIwsq8wsG9AL6GBsBAReRKQU1HS7YMzFPJgCQiJiUjJyisqqXm0VD0BgBJnMljGCQmpRSFXSs36wTOFyumlOoXCK1G41sk26CL6dQx50uXgxIzaUOK%2BPhMyJ82RGFR5KZjWa2KpuKSsKmPWqWWJbJZ6LZw05cWpMK6dN6gsZg1JaPqZyWEoY6wgkBQBFw8m420ezwOTCAA&config=JYWwDg9gTgLgBAbzgEwKYDNgDtUGEJaYDmcAvnOlBCHAOQCuWEAxgM6u0BQnqAHpLBQYAhvQA28NJhz5CwIgAoEnOHCjjUrAFxwA2itV7azeqxjUAtOrGpaAGkRxmEMdB20oqZLTIBdA-6kAJRAA&options=N4IgzgLgTglgxhEAuaBXApgXyA)

**Comment by userquin** [comment]
#297 next release will fix it

**Comment by chu121su12** [comment]
The current css need rework due to shadow-inner is currently only part of boxShadow theme.

https://github.com/antfu/unocss/blob/3551ad5c45ca1701c0718d12427af1f54ab2b1b6/packages/preset-mini/src/theme/misc.ts#L22-L31

https://github.com/antfu/unocss/blob/3551ad5c45ca1701c0718d12427af1f54ab2b1b6/packages/preset-mini/src/rules/shadow.ts#L29-L41

**Comment by zirbest** [comment]
This is the cause of the problem `shadow-2xl` not affect
```diff
 export const boxShadow = { 
   'DEFAULT': '0 1px 3px 0 rgba(var(--un-shadow-color), 0.1), 0 1px 2px 0 rgba(var(--un-shadow-color), 0.06)', 
   'sm': '0 1px 2px 0 rgba(var(--un-shadow-color), 0.05)', 
   'md': '0 4px 6px -1px rgba(var(--un-shadow-color), 0.1), 0 2px 4px -1px rgba(var(--un-shadow-color), 0.06)', 
   'lg': '0 10px 15px -3px rgba(var(--un-shadow-color), 0.1), 0 4px 6px -2px rgba(var(--un-shadow-color), 0.05)', 
   'xl': '0 20px 25px -5px rgba(var(--un-shadow-color), 0.1), 0 10px 10px -5px rgba(var(--un-shadow-color), 0.04)', 
-  '2xl': '25px 50px -12px rgba(var(--un-shadow-color), 0.25)',
+  '2xl': '0 25px 50px -12px rgba(var(--un-shadow-color), 0.25)',
   'inner': 'inset 0 2px 4px 0 rgba(var(--un-shadow-color), 0.06)', 
   'none': 'none', 
 } 
```

**Comment by antfu** [comment]
Nice spotting, PR welcome!
