### ISSUE TITLE
attr:pos no effect

### ISSUE THREAD

**Issue by 729902288** [antfu/unocss#313]
attr: pos no effect

https://unocss.antfu.me/?html=DwEwlgbgBAxgNgQwM5ILwHIAuBTAHpgWhmwDscAndAPiigChbgAHKAIwHMD3yFxTMMmAPYFyUAGbkhAWwKs4AV2wEALAAY16KEyFp0STGBgBrAJ5RhTApqoJWMENnHsAFmABWx4AHomVBlDMUC4EAIwAzGoQLmxC5I7kYbb2Pn50PuAQVEA&config=JYWwDg9gTgLgBAbzgEwKYDNgDtUGEJaYDmcAvnOlBCHAOQCuWEAxgM6u0BQnqAHpLBQYAhvQA28NJhz5CwIgAoEnOHE6kAlEA&options=N4IgzgLgTglgxhEAuAZgQwDZgKYF8g

**Comment by antfu** [comment]
I seem we didn't support that. Why you want it?

**Comment by 729902288** [comment]
hope to support the pos for attr, thanks!

**Comment by antfu** [comment]
Ok, that sounds resonable to support both `pos=` and `position=`. PR welcome
