### ISSUE TITLE
please，how to set keyframes in theme about unocss.config.js ?

### ISSUE THREAD

**Issue by 729902288** [antfu/unocss#315]
I want to set an custom's animation in theme,but I don't how to do? 

https://unocss.antfu.me/?html=DwEwlgbgBAxgNgQwM5ILwHIAuBTAHpgWhmwDscAndAPiigChbgAHKAIwHMD3yFxTMMmAPYFyUAGbkhAWwKs4AV2wEALAAY16WIhQYkmMDADWATyjCmBTVQSsYIbOPYALMACsjwAPRMqDKMzayGjoAO4EAOxqTLhQCCRg0gg4BKFg7Oxw2FocGFJIyurWaRlZ3r7%2Bgc4EAIwAzGoQzmxC5A7ktTZ25TT03uAQVEA&config=JYWwDg9gTgLgBAbzgEwKYDNgDtUGEJaYDmcAvnOlBCHAOQCuWEAxgM6u0BQnqAHpLBQYAhvQA28NJhz5CwIgAoEnOHBgALVCFQAuRCtVw%2BMVFmR7lhwwGtUAT0rDtrCwauqA7vKJjd%2B9%2B60AAwApAA0cACMQaG0FmpQwlis6NAgerRUMMImCgC0AMxoRACUtGRhbgF0AKyx8TCJyalQ6XRZOagKBUHFZRVVVqSDAwFJoDnABK7VcF5EPn6084tRrEbCrKh52HkQ9PDY0sAmtJUBw0MGl3CcpCVAA&options=N4IgzgLgTglgxhEAuAZgQwDZgKYF8g

**Comment by userquin** [comment]
something like this https://imgur.com/MLAgyLG?

**Comment by 729902288** [comment]
还是希望，能支持像tailwind或windicss的keyframes的语法，这样，以便减少我们转换学习的成本，谢谢

**Comment by userquin** [comment]
@729902288 added support for windicss and tailwind object format: https://imgur.com/sNJiZUs

**Comment by 729902288** [comment]
![image](https://user-images.githubusercontent.com/20468762/148898300-53ad4c70-5a87-4dca-adfa-cd95be694ad2.png)

**Comment by 729902288** [comment]
这个动效，好像还是出不来？
https://unocss.antfu.me/?html=DwEwlgbgBAxgNgQwM5ILwHIAuBTAHpgWhmwDscAndAPiigChbgAHKAIwHMD3yFxTMMmAPYFyUAGbkhAWwKs4AV2wEALAAY16KEyFp0STGBgBrAJ5RhTApqhUErGCGzj2ACzAArY8AD0TKgxQzLCIKBgA7gQA7GpMuFAIJGDSCDgE4WDs7HDYWhwYUkjK6jZUGVk5vv6Bwa4EAIwAzGoQrmxC5E7kDXYOVTT0vuAQVEA&config=JYWwDg9gTgLgBAbzgEwKYDNgDtUGEJaYDmcAvnOlBCHAOQCuWEAxgM6u0BQnqAHpLBQYAhvQA28NJhz5CwIgAoEnOHBgALVCFQAuRCtVxhWUMJjACe5YcMBrVAE9Kw7aysGbqgO7yiY3fqenrQADACkADQAjCHhtFZqUMas6NAgerRUMGaoCgC0AMxoRACUtGQRHkF0AKxxCTBJWClpGVk5CgUhxWUVVTakEdVw-X1ByPRJ5gRugdU%2BRH4BtAUclUGkVZuq2yOkJUA&options=N4IgzgLgTglgxhEAuAZgQwDZgKYF8g

**Comment by 729902288** [comment]
@userquin  谢谢您，改为string类型，就可以了。但希望能支持object类型就更好了。

**Comment by txw2018** [comment]
请问这个有文档看怎么配置吗？animation-iteration-count 不知道怎么配置
