### ISSUE TITLE
Does the Nuxt package allow setting a prefix e.g. so that 'placeholder' attributify doesn't conflict in <input/>?

### ISSUE THREAD

**Issue by SebJansen** [antfu/unocss#319]
https://github.com/antfu/unocss/tree/main/packages/nuxt

A "prefix" option or the like isn't listed under the configuration options.

Does the documentation exhaustively list all configuration options or is it just a subset of all the available configuration keys?

It's also unclear to me how to only activate a preset like Windi, because only the default Uno preset seems to be available under the Nuxt package.

**Comment by userquin** [comment]
Try using `preprocess`:
```ts
import { defineNuxtConfig } from 'nuxt3'

const prefixRE = /uno[:-]/

export default defineNuxtConfig({
  vite: false,
  buildModules: [
    '@unocss/nuxt',
  ],
  unocss: {
    attributify: true,
    icons: true,
    components: false,
    shortcuts: [
      ['btn', 'px-4 py-1 rounded inline-block bg-teal-600 text-white cursor-pointer hover:bg-teal-700 disabled:cursor-default disabled:bg-gray-600 disabled:opacity-50'],
    ],
    preprocess: m => prefixRE.test(m) ? m.replace(prefixRE, '') : '',
  },
})
```

**Comment by SebJansen** [comment]
thank you @userquin 

thank you for sharing your solution, I stumbled upon a different one, maybe you have something to say about it
I couldn't get your solution to work, the attributify props didn't apply any styling, and I don't get any error messages, mind you I didn't set `vite: false` because that would give me an error about uno.css not being able to be imported 

what would you say are the advantages of setting `preprocess`, instead of manually specifying `presets`?

`import {defineNuxtConfig} from 'nuxt3'
import { presetUno, presetAttributify } from 'unocss'

export default defineNuxtConfig({
    buildModules: [
        '@unocss/nuxt',
    ],
    unocss: {
        preflight: true,
        icons: true,
        components: true,
        autoImport: true,
        presets: [
            presetAttributify({ prefix: 'u-', prefixedOnly: true}),
            presetUno(),
        ],
    },
})
`

**Comment by SebJansen** [comment]
I closed the issue because there's a solution

**Comment by userquin** [comment]
@SebJansen can you share it here?

**Comment by SebJansen** [comment]
> _A "prefix" option or the like isn't listed under the configuration options._

It isn't listed in the docs, but it is accepted, as seen in code snippet that I shared

> _Does the documentation exhaustively list all configuration options or is it just a subset of all the available configuration keys?_

It is only a subset, so many more keys are accepted, such as the prefix option

> _It's also unclear to me how to only activate a preset like Windi, because only the default Uno preset seems to be available under the Nuxt package._

The code snippet shows how to manually enable any preset for Nuxt 3

**Comment by userquin** [comment]
@SebJansen thank you very much, I'll ping someone on the repo to add some hints.
