### ISSUE TITLE
vscode Extension not autocomplete

### ISSUE THREAD

**Issue by macheteHot** [antfu/unocss#320]
1. when use presetAttributify  vscode Extension not autocomplete 

2. when has special word , like <code>color-#0f0 </code>  not autocomplete
![Kapture 2021-12-25 at 17 20 34](https://user-images.githubusercontent.com/26652329/147382097-e9ffd10b-99a7-4b8b-ab3e-5b6700b528b9.gif)

**Comment by antfu** [comment]
It's intended to be. Since you can't get a finite list of dynamic classes. We are unlikely to support it, unless someone comes up with some nice solutions.
