### ISSUE TITLE
Not detecting classes for components used in markdown

### ISSUE THREAD

**Issue by alexgrozav** [antfu/unocss#33]
Hey @antfu! 

First of all, thank you for all the wonderful assets you're providing to Front-End Developers everywhere. I'm working on integrating unocss in https://github.com/inkline/inkline and have started creating a preset based on the default uno preset.

The issue I've run into is the following: The class detection works wonders when used in a `.vue` file, but it doesn't work at all in components used in a `.md` file.

Any chance you could look into it?

Additional details:
**vite.config.js**
<img width="3200" alt="image" src="https://user-images.githubusercontent.com/6179477/139684724-8584d55b-73a4-4c03-9fe5-9a8efdf275cf.png">

Currently have only one resolver, for any background.
<img width="887" alt="image" src="https://user-images.githubusercontent.com/6179477/139684872-1089ef0b-439e-4d21-a5c9-13904eb3de00.png">

**Comment by userquin** [comment]
Add md file pattern on include option on unocss plugin above presets option, just copy patterns from here https://github.com/antfu/unocss/blob/main/packages/vite/src/utils.ts#L4 and add md pattern

**Comment by userquin** [comment]
Upps, it is there, should work, in a few hours I can take a look...

**Comment by hannoeru** [comment]
This is plugin order issue, put this plugin under `vite-plugin-md` should works.

**Comment by antfu** [comment]
Close due to inactive
