### ISSUE TITLE
Use real iframe for playground demo

### ISSUE THREAD

**Issue by pmiguelmartins** [antfu/unocss#35]
The media queries aren't work

[playground](https://unocss.antfu.me/?html=DwEwlgbgBAFgtAMwK4BsVQC4FMAeG4DGWAdtgE5QIq5QDOW1B%2BxA9sVlALYCGcAjAAYAfACgoUUJCgEU3WrQC8AImx44AczJYSUHCgBcq-Hq4hDufABY9SoQBUstbFyzhuUAI5IsZMI%2BAA9OAQooHBQkA&config=JYWwDg9gTgLgBAbzgEwKYDNgDtUGEJaYDmcAvnOlBCHAOQCuWEAxgM6u0BQnqAHpLBQYAhvQA28NJhz5CwIgAoEnOHCjjUrAFxwA2itV7azeqxjUAtOrGpaAGkRxmEMdB20oqZLTIBdA-6kAJRAA&options=N4IgzgLgTglgxhEAuaBXApgXyA)

`  <div class="text-green xl:text-xl md:text-4xl">Teste media queries</div>`

**Comment by antfu** [comment]
The functionality is indeed working. The problem is only for the playground, we are using a web component instead of a real iframe to show the rendering result, in which you need to resize the window to see the media query change. This is something we could improve, PR welcome.

**Comment by pmiguelmartins** [comment]
I use this in a Vue app and still doesn't work

Can you take a look so I can guarantee that the problem is mine 

Thanks

**Comment by antfu** [comment]
I think it generated the correct output:
![image](https://user-images.githubusercontent.com/11247099/139722674-dd006955-c9e5-4405-9c72-f2ce9a340b66.png)

**Comment by pmiguelmartins** [comment]
Ok ...
Thanks and sorry for the inconvenience ...

PS : What a great work .... thanks
