### ISSUE TITLE
minmax repeat css generation issue

### ISSUE THREAD

**Issue by Adam-Collier** [antfu/unocss#359]
Hi guys, I'm currently having an issue with the css generated from using repeat and minmax in grid-template-columns. 

Given:
```html
grid-cols-[repeat(auto-fit,minmax(275px,0.5fr))]
```

I would expect it to output:
```html
grid-template-columns: repeat(auto-fit, minmax(275px, 0.5fr));
```

however, I am currently getting (notice how the commas are missing in repeat and minmax):
```html
grid-template-columns: repeat(auto-fit minmax(275px 0.5fr));
```

Am I missing something here or is this a bug?

**Comment by antfu** [comment]
with the latest version it should be fixed already

**Comment by zirbest** [comment]
use 
``` html
<div grid="~ cols-[repeat(auto-fit,minmax(275px,0.5fr))]" ...>
<!-- or -->
<div  grid class="grid-cols-[repeat(auto-fit,minmax(275px,0.5fr))]" ...>
```

[REPL](https://unocss.antfu.me/?html=DwEwlgbgBAFgtAMwK4BsVSgcwE5hAXgCIA-LAQwAc4AWKAYwHsUBnOAbWwFMLOyAXABRkkfBojB8ANAFswAO2lkAHgIBMAdgCsFJZIAMAOk0JsASlMBdQgD4AUBlCQoAIziqXmOM5RJOALgBGPRcvH04AvwA2YOYYMhAGAHc4FEwoWPik0N8ATigKVT1rYAB6cAg7B3KQ92dPb19A4NcG8KiYuITk1PTOrNa8gqLS8sqoR2hXWvqwppDWiOjezO60jK7szkHC4rLIMYmaj025lrDFjpWUtb7kgfydkf37ceqp49bTzYvljZ71-phbbDPYVWxPCpAA&config=JYWwDg9gTgLgBAbzgEwKYDNgDtUGEJaYDmcAvnOlBCHAOQCuWEAxgM6u0BQnqAHpLBQYAhvQA28NJhz5CwIgAoEnOHCjjUrAFxwA2itV7azeqxjUAtOrGpaAGkRxmEMdB20oqZLTIBdOwaqgXDBegD0AHowfDAWCgA6yADUAJRxAHSpACRhDgq6dsgOWMIgqP6hjlDCAO4Ayqg2zOZQDiZQnlgwDU0tDgBuwlDAwl0AEqPINlCsDjAAFqhlZClwALwAfIiVzlisLqjpyMBQCoPDozATWFOoMymVnjD0UFiqAAZZCCVl5AA%2BcC%2ByDCACZ-oCENV6o1UM1oOCvu1Ot0YXCoOCLFsvucRuNJtNWLoAAy%2BdIgYQwZiLdFwAA8FjgAK%2BCyWhwARp5hABrSDYGCsdKsECkd4hQzi0KkXzBAzS0gpIA&options=N4IgzgLgTglgxhEAuaBXApgXyA)

**Comment by Adam-Collier** [comment]
Sweet, yep I was slightly behind! Thanks
