### ISSUE TITLE
Regression from `0.19.0` onwards while using attributify with custom prefix

### ISSUE THREAD

**Issue by bhvngt** [antfu/unocss#364]
My code that was using `attributify` with custom prefix has stopped working since `v0.19.0` till the latest `v0.20.2`.

I have created a [test site](https://stackblitz.com/edit/sveltekit-21npxu?file=package.json) for your reference.

With `0.18.1` - `red` and `blue` backgrounds are displayed based on the screen width. The same stops working once you upgrade to `0.19.0` and beyond.

**Comment by userquin** [comment]
@bhvngt can you resize the panel? it is working but since bg red and blue are scoped to media `sm` and `md` the color is gray: https://imgur.com/O8C0KyX

**Comment by userquin** [comment]
I don't know the exact version where we fix variants, that were wrong, the PR fixing it was https://github.com/antfu/unocss/pull/263: we're doing some refactors, so between `0.18.1` and `0.20.2` versions maybe we have some regresion.

/cc @chu121su12

**Comment by bhvngt** [comment]
> @bhvngt can you resize the panel? it is working but since bg red and blue are scoped to media `sm` and `md` the color is gray: https://imgur.com/O8C0KyX

Yes this version of my test works with 0.18.1. Gray is the default background color. If I upgrade the version to `0.20.2` it stops working.

https://user-images.githubusercontent.com/79074469/147851109-955fe74a-0e79-4f2a-b27a-a470f76e0eb6.mov

> I don't know the exact version where we fix variants, that were wrong, the PR fixing it was #263: we're doing some refactors, so between `0.18.1` and `0.20.2` versions maybe we had some regresion.
> 
> /cc @chu121su12

I tried using `at-` and `min-`. But that too does not seem to be working with `0.20.2`. They work with `0.18.1`. So not too sure if this #263 is the culprit to the regression.

**Comment by userquin** [comment]
@bhvngt sorry, I have seen the 0.20.2 version on the reset but reviewing the package.json file the unocss version is the old one...

**Comment by bhvngt** [comment]
Ohh. My bad. I had it earlier set it with `0.18.1`. Now I have set it as `0.20.2`.

**Comment by userquin** [comment]
@bhvngt check this: https://stackblitz.com/edit/sveltekit-w558hl

You can remove the prefix on the attributify plugin and add a preprocessor, just check the `unocss.config.ts` config file.

**Comment by bhvngt** [comment]
> @bhvngt check this: https://stackblitz.com/edit/sveltekit-w558hl
> 
> You can remove the `prefix` option on the `attributify` plugin and add a `preprocess`, just check the `unocss.config.js` config file.

Thanks @userquin This is a good workaround.

**Comment by chu121su12** [comment]
The css looks fine. Can you show the generated css?

![11981445-2166-42B0-8E68-21737E984FD2](https://user-images.githubusercontent.com/379924/147851488-cd91e0c5-2db3-4ff2-b68a-d740ad2fe647.jpeg)

https://unocss.antfu.me/?html=DwCwjAUAxgNghgZwQXgEQCMDmBaTAnOAT1QgFcA7Ae2wQFs0tt0ZSBTEi62gEwZz1bcSAPhCsYMSsAD04YUA&config=JYWwDg9gTgLgBAbzgEwKYDNgDtUGEJaYDmANHGFKgM6owCqWEZF1tAgjDFMAEYCuMYOgCecAL5x0UCCDgByPowDGVKnIBQqAB6RYKDAEM%2BAG3hpMOfIWBEAFAnVxylGjCoAuOAG1HT56xgOLl4BIWF7f0wtTwAiRQgAWhjxAEoSXycWVwYIWzTfAF10sRSgA&options=N4IgzgLgTglgxhEAuAZgQwDZgKYF8g

**Comment by bhvngt** [comment]
@chu121su12 I too noticed that it works on the playground with `0.20.2`.  So I am not sure if this regression is particular to svelte setup.

**Comment by userquin** [comment]
@bhvngt svelte has a few concepts since it is a compiler and the order the vite plugins and the sveltekit preprocessor plays are complicated.

can you try the same with `vite + svelte`  instead `sveltekit`?

@chu121su12 forget it about regression, since it is a problem with this app framework (`sveltekit`).

**Comment by bhvngt** [comment]
@userquin I am wondering why it would work with `0.18.1` if it is not a regression. I am using the same `sveltekit` version.

**Comment by chu121su12** [comment]
@bhvngt Can I ask another screenshot for the css with the working version?

**Comment by bhvngt** [comment]
Here you go @chu121su12 

![image](https://user-images.githubusercontent.com/79074469/147852094-8a201a1c-2855-4325-b965-e2c2583297bf.png)

**Comment by chu121su12** [comment]
I think it is the option refactor. Can you try using `i-sm=“bg-red”` for the color?

**Comment by chu121su12** [comment]
The prefix might get overridden by icon’s options.

**Comment by bhvngt** [comment]
@chu121su12 You are right. It indeed works with `i-`. After changing the order of presets, I was able to make the entire thing work. Thanks @chu121su12 @userquin for your help.

It might be a good idea to document the expected order.

![image](https://user-images.githubusercontent.com/79074469/147852247-79ad392e-9fd0-4144-9e11-7e652d30a3ac.png)

**Comment by chu121su12** [comment]
@antfu From me, I can think of 2 options:
1. revert the options part of this https://github.com/antfu/unocss/pull/321/commits/585244b987aa29caeb32881799fe5e49b676d615 or
2. change the options to `Record<preset name, options>` and add logic to use the right options in the preset

**Comment by userquin** [comment]
@bhvngt can you test again? 

I update https://stackblitz.com/edit/sveltekit-w558hl removing the `preprocess` and adding the `prefix` using `0.21.0` version an it is working.

**Comment by bhvngt** [comment]
@userquin Yep its working well.. Thanks a ton.
