### ISSUE TITLE
Regression from 0.18.1 to 0.19.0 grid-cols with square brackets is no longer recognized

### ISSUE THREAD

**Issue by deleonio** [antfu/unocss#367]
After update @unocss up to 0.19 and higher, the grid-cols with square brackets is no longer recognized.

```jsx
 <main className="py-2 sm:grid sm:gap-4 sm:grid-cols-[auto,2fr]">
          <aside className="pb-2">
```

**Comment by antfu** [comment]
It's an intentional breaking change. Use `sm:grid-cols-[auto_2fr]` instead

**Comment by deleonio** [comment]
Thanks and happy new year, @antfu

**Comment by deleonio** [comment]
Sorry @antfu , but I does not understand why. Do you have a like for us with more information?

**Comment by antfu** [comment]
See https://github.com/antfu/unocss/issues/359

I don't know why `changelog` does not pick up the `!` marker 🤔
