### ISSUE TITLE
Cssvar is not supported

### ISSUE THREAD

**Issue by zmtlwzy** [antfu/unocss#38]
In windicss ,for example
``` html
<div class="top-$header-height">
<!-- top: var(--header-height); -->
  <span>someThing</span>
</div>
```

**Comment by beetaa** [comment]
> In windicss ,for example
> 
> ```
> <div class="top-$header-height">
> 
>   <span>someThing</span>
> </div>
> ```

exactly what I want, thanks.

**Comment by edwardnyc** [comment]
> In windicss ,for example
> 
> ```
> <div class="top-$header-height">
> 
>   <span>someThing</span>
> </div>
> ```

I didn't find the corresponding matching rule. Could you please send the document?

**Comment by antfu** [comment]
https://windicss.org/features/value-auto-infer.html#variables
