### ISSUE TITLE
when i open http://localhost:4000/__unocss; error : Cannot read properties of undefined (reading 'length')

### ISSUE THREAD

**Issue by qc-z** [antfu/unocss#404]
version: v0.20.4
![image](https://user-images.githubusercontent.com/22362903/148030230-b17948a9-2a20-4110-be84-ca0a7a132ed9.png)

**Comment by userquin** [comment]
@qc-z thx, I'll review what's the error...

**Comment by userquin** [comment]
@qc-z can yout provide a repro? I cannot reproduce the error...

**Comment by qc-z** [comment]
@userquin https://github.com/qc-z/vue-template

**Comment by userquin** [comment]
@qc-z I update unocss to `0.22.0` and it works, I cannot reproduce the error:

![imagen](https://user-images.githubusercontent.com/6311119/149142539-c368aa8a-c03a-4f19-a38d-ae9278a913d9.png)

**Comment by qc-z** [comment]
@userquin You're right. 0.22.0 is no problem，but my version is 0.20.4.
I'll just upgrade it. Thank you.
