### ISSUE TITLE
微信小程序使用报错

### ISSUE THREAD

**Issue by Miofly** [antfu/unocss#412]
我在微信小程序使用 unocss + @unocss/preset-icons 报如下错误，h5上没有问题。
因为微信小程序不支持 svg，所以之前没有使用 Iconify，但发现 @unocss/preset-icons 是以纯 css 来渲染 icon 的，所以尝试了一下，编译在 h5 中没有问题。但小程序上报错，报错如下，把报错的那一行注释掉可以通过编译但 icon 仍旧没有渲染，不知道是否是小程序的内部机制问题，想问下有没有办法对此兼容。
![image](https://user-images.githubusercontent.com/42859910/148209012-df470e33-76d4-470c-a81e-ae27805088c4.png)

`import Unocss from 'unocss/vite';import UnocssIcons from '@unocss/preset-icons';` 

git 报错的源文件路径如下
![image](https://user-images.githubusercontent.com/42859910/148210049-a0ced0c6-7771-47a5-92a7-60cbf34847d8.png)

**Comment by Miofly** [comment]
吐槽下微信小程序，很多东西都不兼容，包括使用 windicss 也是一样，简直是技术的倒退版，但仍旧需要使用，还是希望能够有更好的方法去处理他。

**Comment by antfu** [comment]
You can try to create a preset with the tech that mini apps support. Official support is out-of-scope of this project.

**Comment by zhiyuanzmj** [comment]
vite:css-post 依赖 vite:css 
但不知道为什么 用了uniapp后 [vite:css]插件没有运行 [https://github.com/vitejs/vite/blob/bd4c3a5dcbb20da5cfd93daf38932bccb45a7742/packages/vite/src/node/plugins/css.ts#L161](https://github.com/vitejs/vite/blob/bd4c3a5dcbb20da5cfd93daf38932bccb45a7742/packages/vite/src/node/plugins/css.ts#L161)
所以[vite:css-post]插件 这行代码报错了 
[https://github.com/vitejs/vite/blob/bd4c3a5dcbb20da5cfd93daf38932bccb45a7742/packages/vite/src/node/plugins/css.ts#L290](https://github.com/vitejs/vite/blob/bd4c3a5dcbb20da5cfd93daf38932bccb45a7742/packages/vite/src/node/plugins/css.ts#L290)
我的解决办法是 使用 vue-scoped 模式
`
Unocss({
    mode: 'vue-scoped',
    presets: [
      presetIcons(),
    ],
})
`
在小程序里使用图标效果非常好， 就差自定义图标配置了 那就完美了 @Miofly

**Comment by Miofly** [comment]
> vite:css-post 依赖 vite:css 但不知道为什么 用了uniapp后 [vite:css]插件没有运行 https://github.com/vitejs/vite/blob/bd4c3a5dcbb20da5cfd93daf38932bccb45a7742/packages/vite/src/node/plugins/css.ts#L161 所以[vite:css-post]插件 这行代码报错了 https://github.com/vitejs/vite/blob/bd4c3a5dcbb20da5cfd93daf38932bccb45a7742/packages/vite/src/node/plugins/css.ts#L290 我的解决办法是 使用 vue-scoped 模式 `Unocss({ mode: 'vue-scoped', presets: [ presetIcons(), ], })` 在小程序里使用图标效果非常好， 就差自定义图标配置了 那就完美了 @Miofly

大佬强，亲测可用，我的业务场景也是uniapp开发，微信小程序真是很多不支持，目前windicss的 \ 反斜杠在微信小程序上也是让人头疼的问题。

**Comment by zhiyuanzmj** [comment]
// 这是我的 postcss.config.js
const { uniPostcssPlugin } = require('@dcloudio/uni-cli-shared')
module.exports = {
  syntax: 'postcss-scss',
  plugins: [
    require('postcss-import')({
      resolve(id) {
        if (id.startsWith('~@/')) {
          return path.resolve(process.env.UNI_INPUT_DIR, id.substr(3))
        } else if (id.startsWith('@/')) {
          return path.resolve(process.env.UNI_INPUT_DIR, id.substr(2))
        } else if (id.startsWith('/') && !id.startsWith('//')) {
          return path.resolve(process.env.UNI_INPUT_DIR, id.substr(1))
        }
        return id
      },
    }),
    require('postcss-class-rename')({
      '\\\\:': '--',
      '\\\\/': '--',
      '\\\\.': '--',
      '.:': '--',
      '\\*': '--',
    }),
    uniPostcssPlugin(),
    require('autoprefixer')(),
  ],
}

**Comment by Miofly** [comment]
> 这是我的 postcss.config.js
> 
> ```
> const { uniPostcssPlugin } = require('@dcloudio/uni-cli-shared')
> module.exports = {
>   syntax: 'postcss-scss',
>   plugins: [
>     require('postcss-import')({
>       resolve(id) {
>         if (id.startsWith('~@/')) {
>           return path.resolve(process.env.UNI_INPUT_DIR, id.substr(3))
>         } else if (id.startsWith('@/')) {
>           return path.resolve(process.env.UNI_INPUT_DIR, id.substr(2))
>         } else if (id.startsWith('/') && !id.startsWith('//')) {
>           return path.resolve(process.env.UNI_INPUT_DIR, id.substr(1))
>         }
>         return id
>       },
>     }),
>     require('postcss-class-rename')({
>       '\\\\:': '--',
>       '\\\\/': '--',
>       '\\\\.': '--',
>       '.:': '--',
>       '\\*': '--',
>     }),
>     uniPostcssPlugin(),
>     require('autoprefixer')(),
>   ],
> }
> ```

大佬的package.json是否能发下。我不知道是不是因为包版本的问题，我这边配置之后出现报错
![image](https://user-images.githubusercontent.com/42859910/148539445-22ad63f7-cdb8-4f8a-91ff-d90b8870f783.png)

**Comment by zhiyuanzmj** [comment]
> > 这是我的 postcss.config.js
> > ```
> > const { uniPostcssPlugin } = require('@dcloudio/uni-cli-shared')
> > module.exports = {
> >   syntax: 'postcss-scss',
> >   plugins: [
> >     require('postcss-import')({
> >       resolve(id) {
> >         if (id.startsWith('~@/')) {
> >           return path.resolve(process.env.UNI_INPUT_DIR, id.substr(3))
> >         } else if (id.startsWith('@/')) {
> >           return path.resolve(process.env.UNI_INPUT_DIR, id.substr(2))
> >         } else if (id.startsWith('/') && !id.startsWith('//')) {
> >           return path.resolve(process.env.UNI_INPUT_DIR, id.substr(1))
> >         }
> >         return id
> >       },
> >     }),
> >     require('postcss-class-rename')({
> >       '\\\\:': '--',
> >       '\\\\/': '--',
> >       '\\\\.': '--',
> >       '.:': '--',
> >       '\\*': '--',
> >     }),
> >     uniPostcssPlugin(),
> >     require('autoprefixer')(),
> >   ],
> > }
> > ```
> 
> 大佬的package.json是否能发下。我不知道是不是因为包版本的问题，我这边配置之后出现报错 ![image](https://user-images.githubusercontent.com/42859910/148539445-22ad63f7-cdb8-4f8a-91ff-d90b8870f783.png)

H5好像有问题 , H5的时候就不转换吧...
```
const { uniPostcssPlugin } = require('@dcloudio/uni-cli-shared')
module.exports = {
  syntax: 'postcss-scss',
  plugins: [
    require('postcss-import')({
      resolve(id, basedir, importOptions) {
        if (id.startsWith('~@/')) {
          return path.resolve(process.env.UNI_INPUT_DIR, id.substr(3))
        } else if (id.startsWith('@/')) {
          return path.resolve(process.env.UNI_INPUT_DIR, id.substr(2))
        } else if (id.startsWith('/') && !id.startsWith('//')) {
          return path.resolve(process.env.UNI_INPUT_DIR, id.substr(1))
        }
        return id
      },
    }),
    ...(process.env.UNI_PLATFORM !== 'h5'
      ? [
          require('postcss-class-rename')({
            '\\\\:': '--',
            '\\\\/': '--',
            '\\\\.': '--',
            '.:': '--',
            '\\*': '--',
          }),
        ]
      : []),
    uniPostcssPlugin(),
    require('autoprefixer')(),
  ],
}

```

**Comment by KDWangBoss** [comment]
我也遇到了这个问题，你的解决了吗😂

**Comment by KDWangBoss** [comment]
<img width="854" alt="image" src="https://github.com/unocss/unocss/assets/40023056/00638b0e-ce82-43a2-b5c8-e4ab24fa3f81">
