### ISSUE TITLE
Option to set a 'manual' scope class for additional specificity weight.

### ISSUE THREAD

**Issue by mrwokkel** [antfu/unocss#43]
When working with typography systems (like tailwinds) on areas of markup not under developers control, it good to have the ability to scope the utility classes produced.

So `.p4 {}` becomes `.my-custom-scope .p4 {}`.

Tailwind implements this with the 'important' config option, which can be set to a css classname. But I think it is not the best name for such an option.

The idea for a custom scope to maintain control of utility classes, even when used inside a typesystem.

Example:
`.my-custom-scope .p4 {}` must be able to override `.typesystem h1 { padding:... }`

**Comment by antfu** [comment]
I think the newly introduced `Layers` features could solve what you need https://github.com/antfu/unocss#layers

**Comment by mrwokkel** [comment]
I am afraid that `Layers` can not solve this. `Layers` is about order in the cascade. Where my example is about specificity weight.

In the above example, even when `.p4 {}` (without manual scope) comes after `.typesystem h1 { padding... }` it can not override because `.typesystem h1` resolves to a weight of "11" where `.p4` only resolves to a weight of "10". So `.typesystem h1` will always 'win', no mater the order.

One can replace `.typesystem` with `.prose` in the examples for clarity on the use case.

**Comment by liaoyinglong** [comment]
with config 
```
 postprocess: (t) => {
    t.selector = `html ${t.selector}`
    return t
  },
```

generate css file will like 

```
html .p4{}
```
