### ISSUE TITLE
VS-Code plugin loading is strangely buggy

### ISSUE THREAD

**Issue by Zachiah** [antfu/unocss#431]
[This](https://github.com/Zachiah/demonstrate-uno-solid-bug) is just an example repo, I'm pretty sure this will work anywhere that has uno.

Ok so this is the weird issue: This config loads
```
import Unocss from 'unocss/vite'
import { presetUno, presetAttributify } from 'unocss'

export default {
  plugins: [
    Unocss({
      presets: [
        presetAttributify({ /* preset options */}),
        presetUno(),
        // ...custom presets 
      ]
    })
  ]
}
```

this config, which is exactly the same but with a comment at the beggining...
doesn't load:

```
// // THIS FILE IS JUST FOR UNOCSS VSCODE TO RECOGNIZE THAT UNO IS USED
// // PLEASE DON'T REMOVE IT

// import { defineConfig } from "vite";
// import Unocss from "unocss/vite";
// import { presetIncmix } from "./packages/theme/src/unoConfig";
// import { presetAttributify, presetUno } from "unocss";

// export default defineConfig({
//   plugins: [
//     Unocss({
//       presets: [
//         presetIncmix(),
//         presetAttributify({}),
//         presetUno({}),
//       ],
//     }),
//   ],
//   build: {
//     target: "esnext",
//     polyfillDynamicImport: false,
//     outDir: "../docs",
//   },
// }); 

import Unocss from 'unocss/vite'
import { presetUno, presetAttributify } from 'unocss'

export default {
  plugins: [
    Unocss({
      presets: [
        presetAttributify({ /* preset options */}),
        presetUno(),
        // ...custom presets 
      ]
    })
  ]
}
```

by the way, sorry about the weird comment, but I'm not sure which comments will trigger the problem and which won't. I'll try to figure out exactly what causes the problem...

here is a video demonstrating what I'm getting https://ufile.io/wiz89797

**Comment by Zachiah** [comment]
Sorry about that video didn't realize you'd have to download it, here is an unlisted yt video https://www.youtube.com/watch?v=uuGwza0wVHc

**Comment by antfu** [comment]
Why do you need the comments tho? The config extraction is done by a regex rewrite to get the nested config object.

**Comment by Zachiah** [comment]
Thanks for your reply! I don't need the comment, it's just that I've been having some very hard to debug issues and this is the only reproducible one I found... Is there any kind of support form or anything? Or would it be okay if I asked a couple of questions sort of unrelated to this issue but sort of related at the same time and this thread? Thanks again for your speedy reply!

**Comment by Zachiah** [comment]
Specifically I've been having issues where some attributify attributes work with custom rules  and others don't. I've also been getting error s when passing presets about how the preset can't access properties of undefined, whether or not I pass an empty config object

**Comment by Zachiah** [comment]
Should I raise detailed issues for each problem? I'm hesitant to just because I suspect the issue is on my end

**Comment by antfu** [comment]
Should you can create an issue for each with minimal reproduction.

**Comment by Zachiah** [comment]
Sorry! I just was in the process of removing my comments I just discovered it was due to unocss@0.21 instead of unocss@0.22... Didn't even cross my mind because the errors were nothing like what I'd expect and it worked in ts, but just got it working by upgrading. Thanks again
