### ISSUE TITLE
Issue building with vite

### ISSUE THREAD

**Issue by Zachiah** [antfu/unocss#432]
![image](https://user-images.githubusercontent.com/50641830/148496924-51a4ce8a-7f61-4e68-a7d0-c87a3985daa1.png)

Can't build the project when using vite with unocss... Not sure exactly what's going on. Here is a repro https://github.com/Zachiah/uno-css-bug-2-demo  I've made sure the versions are all latest (lol)

**Comment by userquin** [comment]
@Zachiah you must include `import 'uno.css'` on your `main.ts` module and also add the `main.tsx` since you are not using it:
```shell
F:\work\projects\quini\GitHub\issue-repro\uno-css-issue-432-repro>pnpm run build

> uno-css-bug-2-demo@0.0.0 build F:\work\projects\quini\GitHub\issue-repro\uno-css-issue-432-repro
> tsc && vite build                                                                               

vite v2.7.10 building for production...
✓ 5 modules transformed.
../docs/assets/favicon.63a26457.svg   1.50 KiB
../docs/index.html                    0.47 KiB
../docs/assets/index.f3280459.js      0.86 KiB / gzip: 0.50 KiB
../docs/assets/index.2b4d7fa6.css     0.17 KiB / gzip: 0.14 KiB
```

**Comment by Zachiah** [comment]
Ok, Thanks!
