### ISSUE TITLE
add more behaviors

### ISSUE THREAD

**Issue by userquin** [antfu/unocss#45]
Just a reminder we need to add (from https://windicss.org/utilities/behaviors.html):
- **Outline**: `Outline Solid` and `Outline Dotted`
- **Overflow** and **Overscroll Behavior**
- **Placeholder Color**
- **Placeholder Opacity**
- **Resize**
- **User Select**
- **Screen Readers Access**

**Animations** will be included in its own module, @antfu is working to `hoist` `keyframes`.

**Comment by edwardnyc** [comment]
Yeah, keyframes are really tricky. It seems difficult to implement the current generator simply.(Considering that the user is easy to understand)

Unocss is magical.

**Comment by userquin** [comment]
The same response I receive from `@antfu` when talkiing about  keyframes.

Feel free to add features listed  above, yestarday I was working on it but you make the PR, some of them (last 3) can be included directly.

For **Placeholder Opacity** we need the vendors to be included.

**Comment by userquin** [comment]
Another great utility will be to include `question mark` for dev time.

**Comment by antfu** [comment]
FYI, I think I have figured out a balanced approach for @keyframes: 9d95ae6093ac27a12e03f27cc8970642dee29cf5

**Comment by userquin** [comment]
`behaviors.ts`:
- [ ] **Outline Solid**
- [ ] **Outline Dotted**
- [x] **Overflow** and **Overscroll Behavior**:  it is on `layout.ts`
- [x] **Placeholder Color**
- [x] **Placeholder Opacity**
- [x] **Resize**: moved to `static.ts`
- [x] **User Select**: moved to `static.ts`
- [x] **Screen Readers Access**: moved to `static.ts`

`animation.ts`:
- [x] **Animations** will be included in its own module, @antfu is working to `hoist` `keyframes`.
- [ ] **Animations**: TODO: support custom speed, duration, delay
