### ISSUE TITLE
请问：rules中，如何设置支持 nth-child(n) 、nth-of-type(n) 、sibling呢？

### ISSUE THREAD

**Issue by 729902288** [antfu/unocss#460]
unocss，变得越来越好了！
请问一下：rules中，如何设置支持 nth-child(n) 、nth-of-type(n) 、sibling呢？

**Comment by antfu** [comment]
https://github.com/antfu/unocss/blob/fb9403ac8b8da8acd6f0124f9c348d60d1c255a3/packages/preset-mini/src/variants/combinators.ts#L8-L9
https://github.com/antfu/unocss/blob/7d0745c8b514b12872e0ccf50ff5b48471ce67b1/packages/preset-mini/src/variants/pseudo.ts#L42-L49
these?
