### ISSUE TITLE
请问有没有办法开启CSS-in-JS模式来动态生成css来提高页面渲染速度

### ISSUE THREAD

**Issue by gggso** [antfu/unocss#469]
如题，想在在使用 unocss的同时，又用 CSS-in-JS 来提升页面的加载渲染速度，或者说已经实现，请告知一下。打扰了

**Comment by antfu** [comment]
https://github.com/antfu/unocss/tree/main/packages/runtime

不太理解你要怎么加快速度，我认知里 CSS-in-JS 只会比纯 CSS 要慢

**Comment by gggso** [comment]
> 

不是这个。这个是不使用任何编译器的情况下，使用unocss。我说的css-in-js指的是在跳转到对应page的时候，才把页面中对应的css以 style的时候注入到head中，这样在应用首次打开的时候就不需要加载所有的css，毕竟css文件也是一个请求,可以优化那么一丢丢首次渲染的速度。
