### ISSUE TITLE
pug support

### ISSUE THREAD

**Issue by red010182** [antfu/unocss#472]
Thanks for creating this awesome project. I'm a pug lover but unfortunately it seems not working with pug. It would be even more fantastic combined with pug. The long class names in pug could turn into line-break attributes thus make it more readable.

Does there any plan to support pug?

Many thanks.

**Comment by antfu** [comment]
https://github.com/antfu/unocss/tree/main/packages/extractor-pug

**Comment by Youdaman** [comment]
Was about to file an issue saying that UnoCSS classes only work in Pug templates if they've already been used in HTML templates, but @unocss/extractor-pug is the solution! Thank you @antfu 🙏
