### ISSUE TITLE
when I use ' mode: vue-scoped ' , the vite faild dev project and  tell me : 'Failed to resolve import "uno.css" from "src\main.ts". Does the file exist?'

### ISSUE THREAD

**Issue by liuv3v6** [antfu/unocss#477]
this my config ,but when I remove 'mode: vue-scoped ', vite works good.
```
export default defineConfig({
  plugins: [Unocss(
    {
      mode: 'vue-scoped',
      presets: [
        presetAttributify({}),
        presetUno()
      ]
    }
  ),vue()],
 .....
})
```

**Comment by userquin** [comment]
@liuv3v6 if you're using `vue-scoped` you **must** remove `import ' uno.css'`  since there is no global css on this mode. 

Anyway, this mode is `WIP: work in progress` yet and maybe removed in a future.

**Comment by antfu** [comment]
`uno.css` is for global mode. In vue scoped mode you don't need it

**Comment by liuv3v6** [comment]
>


> @liuv3v6 if you're using `vue-scoped` you **must** remove `import 'uno.css'` since there is no global css on this mode.
> 
> Anyway, this mode is `WIP: work in progress` yet and maybe removed in a future.

I hope do not remove the function about mode ,because, using the vue-scoped and defineCustomElement (vue 3.2 api)  can generate web components with css，it useful!
