### ISSUE TITLE
[playground] the scrollbars are not accesible

### ISSUE THREAD

**Issue by CharlesOkwuagwu** [antfu/unocss#493]
When you try to access the scrollbar, particularly the horizontal scrollbars, the pane divider is activated and the scrollbar cannot be clicked/scrolled.

**Comment by userquin** [comment]
@CharlesOkwuagwu I Will fix it later

**Comment by userquin** [comment]
@CharlesOkwuagwu the problem is with vertical scrollbar or horizontal one? I have this problem with the vertical scrollbar sonce the split pane spans 10px in both left and right but for horizontal ones there is no such problem

**Comment by CharlesOkwuagwu** [comment]
I see it on the horizontal scrollbar

**Comment by userquin** [comment]
@CharlesOkwuagwu so the problem is the vertical overflow, the horizontal scroll is at the bottom and so the horizontal scroll is off screen, rigth? Fixing the 3 split panes...

I mixed this with the `inpector` sorry.

**Comment by userquin** [comment]
@CharlesOkwuagwu

![imagen](https://user-images.githubusercontent.com/6311119/149661822-7ef90ada-cd35-4306-9634-ed88a67cd465.png)
