### ISSUE TITLE
建议：将variantMatcher('children', input => `${input}>*`)中的children，改为childs，要不然会与react的children冲突

### ISSUE THREAD

**Issue by 729902288** [antfu/unocss#500]
建议：将variantMatcher('children', input => `${input}>*`)中的**children，改为childs**，要不然会与react的children冲突
![image](https://user-images.githubusercontent.com/20468762/149684959-bee046bf-9abc-4852-aa8b-4ac78c733993.png)

**Comment by antfu** [comment]
`childs` is not a valid English words, use `uno-children` instead.

**Comment by 729902288** [comment]
@antfu ，您好，请发布提交一下，谢谢！
