### ISSUE TITLE
clip-path：circle(),path()......，请问在rules中，不知能否设置？

### ISSUE THREAD

**Issue by 729902288** [antfu/unocss#516]
clip-path：circle(),path()......，请问在rules中，可以设置吗？

**Comment by chu121su12** [comment]
Please open a PR if you want to add feature. Otherwise, you can use

`[clip-path:circle(...)]`

see: https://tailwindcss.com/docs/adding-custom-styles#arbitrary-properties

**Comment by 729902288** [comment]
@chu121su12 ，谢谢您，谢谢。
unocss的功能真好，你们的服务精神更好！
