### ISSUE TITLE
`preset-mini`: Screen Variants With Dash Don't Work Like in WindiCSS

### ISSUE THREAD

**Issue by tuhanayim** [antfu/unocss#547]
I'm not able to use screen variants with dash`(-)` symbol in UnoCSS like in WindiCSS. In WindiCSS, adding dash symbol to the beginning of the variant makes WindiCSS use `max-width` instead of `min-width`. And I'm personally using this feature, a lot. But in UnoCSS, it makes class' values minus number.
> I don't know if it's made like this deliberately or a bug, so i created issue.
I only tested `preset-mini`, i don't know how it works on `preset-windi`.

![image](https://user-images.githubusercontent.com/83988414/151237148-5b54602e-f0ea-4b88-b271-aec358b2062f.png)

**Comment by chu121su12** [comment]
Currently the syntax is `lt-md:px-4`

**Comment by antfu** [comment]
Leading `-` for max-width is not docuemented behaviour (https://windicss.org/features/responsive-design.html) and we will are not going to align it. Use `<` or `lt-` instead.
