### ISSUE TITLE
unocss icon does not render when use in certain way

### ISSUE THREAD

**Issue by weeuwee** [antfu/unocss#578]
Icon does not render will bind to a variable imported from other file
```vue
<template>
  <div class="p-6">
    <h1>Can Render this way</h1>
    <div :class="canRender"></div>
    <h1>Cannot Render this way</h1>
    <div :class="cannotRender"></div>
  </div>
</template>
<script setup lang="ts">
import { cannotRender } from './temp';
const canRender = 'i-carbon:3d-cursor';
</script>
```

Following is a sample of the above
[https://stackblitz.com/edit/nuxt3-unocss-missing-icon?file=app.vue](https://stackblitz.com/edit/nuxt3-unocss-missing-icon?file=app.vue)

**Comment by chu121su12** [comment]
Try adding `@unocss-include` https://github.com/antfu/unocss#scanning

**Comment by weeuwee** [comment]
Thanks! missed that part on the doc
