### ISSUE TITLE
Svelte Integration

### ISSUE THREAD

**Issue by axmad386** [antfu/unocss#6]
Hi, this is awesome css engine. But I have problem when integrate unocss with svelte via `@sveltejs/vite-plugin-svelte`
It's like unocss only scan html file and ignore .svelte extension. Maybe I miss something?

**Comment by aewing** [comment]
After working with uno a bit more I am noticing some strange behaviors with SvelteKit, but I'm not sure they can be easily resolved.
When using dynamic classes, for example `class="i-tabler-{icon}"`, the icon won't be recognized in development unless and until I introduce the full icon name somewhere in the markup. So far I have been working around this by commenting the classname I want to see (i.e. `<!-- i-tabler-bookmark -->`) and saving, but I'd be interested to see if there's a better way.

**Comment by antfu** [comment]
@aewing it's the same constraint with PurgeCSS, Windi CSS, Tailwind JIT - the scanner can't possibly know the dynamic parts at static scanning, refer to: 
- https://windicss.org/guide/extractions.html
- https://tailwindcss.com/docs/optimizing-for-production#writing-purgeable-html

**Comment by lkj4** [comment]
I can't get Unocss to work with SvelteKit (just the normal utility classes in `class='...'`). I've tried in `svelte.config.ts` both...
```
import preprocess from 'svelte-preprocess'
import Unocss from 'unocss/vite'
import { presetUno } from 'unocss'
import { svelte } from '@sveltejs/vite-plugin-svelte'

/** @type {import('@sveltejs/kit').Config} */
const config = {
  preprocess: preprocess(),
  kit: {
    target: '#svelte',
    vite: () => ({ plugins: [svelte(), Unocss({ presets: [presetUno()] })] }),
  },
}

export default config
```
and
```
import preprocess from 'svelte-preprocess'
import Unocss from 'unocss/vite'
import { presetUno } from 'unocss'

/** @type {import('@sveltejs/kit').Config} */
const config = {
  preprocess: preprocess(),
  kit: {
    target: '#svelte',
    vite: () => ({ plugins: [Unocss({ presets: [presetUno()] })] }),
  },
}

export default config
```
paired with a `import 'uno.css'` in `__layout.svelte`'s `<script />` section. I've tested a `bg-blue` on a div.

**Comment by lkj4** [comment]
> @axmad386 your example works as expected in SvelteKit...

Would you mind sharing your `svelte.config.(t|s)s` or just relevant parts. I just can't get SvelteKit to work with uno, trying every combination of the config. Thanks!

**Comment by lkj4** [comment]
Ok, I think I need to add this to the svelte-preprocessor https://github.com/sveltejs/svelte-preprocess/blob/main/docs/preprocessing.md#configuring-preprocessors but would be great if you guys could hint me how /cc @aewing

**Comment by lkj4** [comment]
I've also tried in `svelte.config.js` both ...
```
preprocess: [preprocess(), Unocss({ presets: [presetUno()] })],
```
```
preprocess: [Unocss({ presets: [presetUno()] }), preprocess()],
```
but I don't any get `uno.css` in the build-files (or any of its contents), where is this file? /cc @antfu

**Comment by aewing** [comment]
> > @aewing your example works as expected in SvelteKit...
> 
> Would you mind sharing your `svelte.config.js` or just relevant parts. I can't get SvelteKit to work with uno, I've tried every combination of the config but must do something wrong. Thanks!

Hey, no problem. Here's my `svelte.config.js`:
```js
import preprocess from 'svelte-preprocess';
import Unocss from 'unocss/vite';
import { presetUno, presetAttributify } from 'unocss';
import presetIcons from '@unocss/preset-icons';

/** @type {import('@sveltejs/kit').Config} */
const config = {
	// Consult https://github.com/sveltejs/svelte-preprocess
	// for more information about preprocessors
	preprocess: preprocess(),

	kit: {
		// hydrate the <div id="svelte"> element in src/app.html
		target: '#svelte',
		vite: {
			plugins: [
				Unocss({
					presets: [presetUno(), presetAttributify(), presetIcons()]
				})
			]
		}
	}
};

export default config;
```

and in my `__layout.svelte`:
```svelte
<script>
	import 'uno.css';
	import '@unocss/reset/tailwind.css';
</script>
```

hope that helps!

**Comment by lkj4** [comment]
@aewing thank you so much. First it didn't work and I got again this error, that `uno.css` couldn't be found. But the solution is easy (and for others driving by):

_Restart the dev server or your respective container on __every__ config change!_

Another nice thing in Svelte is how you can do conditional classes, just do `<div class:bg-red={true} />`, super nice 🙂

One thing I still wonder, I do not need to export the attributes or do anything to make it work,  all Tailwind classes work and even my linter does not complain (only with Tachyons classes/attributes it does complain), @antfu how did you that it's works automagically with the tsserver lsp?

**Comment by lkj4** [comment]
Oh wait, this is strange while stuff like `pb-20` or `bottom-0` don't throw any error, something like `absolute` throws following error with tsserver:

```
[ts 2322] [E] Type '{ absolute: true; "pb-20": true; "bottom-0": true; }' is
not assignable to type 'HTMLProps<HTMLDivElement>'.
  Property 'absolute' does not exist on type 'HTMLProps<HTMLDivElement>'.
```

**Comment by esyon** [comment]
> ```js
> presetIcons
> ```

Are the icons working? I used the exact same config, but Icons won't show up...

**Comment by esyon** [comment]
> > > @aewing your example works as expected in SvelteKit...
> > 
> > 
> > Would you mind sharing your `svelte.config.js` or just relevant parts. I can't get SvelteKit to work with uno, I've tried every combination of the config but must do something wrong. Thanks!
> 
> Hey, no problem. Here's my `svelte.config.js`:
> 
> ```js
> import preprocess from 'svelte-preprocess';
> import Unocss from 'unocss/vite';
> import { presetUno, presetAttributify } from 'unocss';
> import presetIcons from '@unocss/preset-icons';
> 
> /** @type {import('@sveltejs/kit').Config} */
> const config = {
> 	// Consult https://github.com/sveltejs/svelte-preprocess
> 	// for more information about preprocessors
> 	preprocess: preprocess(),
> 
> 	kit: {
> 		// hydrate the <div id="svelte"> element in src/app.html
> 		target: '#svelte',
> 		vite: {
> 			plugins: [
> 				Unocss({
> 					presets: [presetUno(), presetAttributify(), presetIcons()]
> 				})
> 			]
> 		}
> 	}
> };
> 
> export default config;
> ```
> 
> and in my `__layout.svelte`:
> 
> ```svelte
> <script>
> 	import 'uno.css';
> 	import '@unocss/reset/tailwind.css';
> </script>
> ```
> 
> hope that helps!

Are the icons working? I used the exact same config, but Icons won't show up...

**Comment by userquin** [comment]
I'm playing with `vite + svelte` but should work with `sveltkit` if you want to check `class:xxx` support: https://github.com/userquin/unocss-svelte-ts

**Comment by lkj4** [comment]
@userquin nice, I'll check it out! Does an `absolute` attribute trigger an error with tsserver/your linter?

**Comment by userquin** [comment]
@lkj4 I'm not a big fun of using attributes, a suggestion is to use `data-***` attributes and add on `preprocess` the logic to remove the `data-` prefix, and so all working.

I'll add some branches to my repo: on `vite + svelte` we should add `unocss/vite` before `@sveltejs/vite-plugin-svelte` and so we can access to the code before transformation, on `sveltekit` I'll ask to `svelte` experts to check how can we do that, if you cannot answer.

On my main branch I updated the configuration, `svelte` seems to not retain the order on class, just adding `!hover:rotate-180` and all works also after refresh or HMR update.

**Comment by userquin** [comment]
I started a discussion here https://github.com/antfu/unocss/discussions/175.

We should move there...

/cc @antfu can you block this (don't close/remove/move it, to keep track the integration)?
