### ISSUE TITLE
add `border`-like and `from-`, `to-`, `via-` supports for cssvar feature.

### ISSUE THREAD

**Issue by beetaa** [antfu/unocss#60]
can you please add `border` support for the variable feature? It's missed in current implementation. thank you. @edwardnyc

**Comment by beetaa** [comment]
and it seems that it will be great if cssvar's mappings can be unified with `default preset`'s utilities mappings.

**Comment by edwardnyc** [comment]
Now we need to use Regexp in each rule to support cssvar functionality. In this case, although the input of our program is more controllable, it is difficult to develop. Users may often give us feedback that some other properties do not support cssvar.

Do you have some good plans for this? [Previous conversation](https://github.com/antfu/unocss/pull/47#discussion_r741605053) @antfu

**Comment by beetaa** [comment]
hi @edwardnyc, THANKS SO MUCH FOR YOUR GREAT WORKS. Personally, I think it should be the responsibilities of users themselves to check if properties support cssvar or not. for UNOCSS itself, it would be great and clear if rules can be maintained in a **UNIFIED** way. @edwardnyc @antfu
