### ISSUE TITLE
hmr: vue sfc update not using pug extractor

### ISSUE THREAD

**Issue by tjk** [antfu/unocss#66]
EDIT: [See latest comment](https://github.com/antfu/unocss/issues/66#issuecomment-962159983) with tracing in [second comment](https://github.com/antfu/unocss/issues/66#issuecomment-962147417).

~~I can put together a minimal repro later unless this is expected?~~

(Refresh fixes the issue -- my stack is loosely based off `vite/packages/playground/ssr-vue`)

**Comment by tjk** [comment]
Okay after doing some traces it looks like the pug extractor is not actually running when the SFC is changed so it doesn't find the proper token.

```
// vite.config.js
...
    Unocss({
      presets: [
        UnoPresetIcons(),
      ],
      extractors: [
        extractorPug(),
        extractorSplit,
      ],
    }),
...
```
On `.vue` file update, `generate` does not see pug extracted tokens (just split)

**Comment by tjk** [comment]
So I'm not familiar enough with `@vitejs/plugin-vue` but it looks like (pug) `extract` should also handle `.vue?vue&type=template&lang.js` somehow -- but it doesn't know that the template has lang pug at that point.

**Comment by antfu** [comment]
I don't have a repo to play with, tried to fix it on 3d308a8717850f33957225850877cdac24eeb370, can you verify if it works for you? Thanks

**Comment by tjk** [comment]
It just emits the raw pug (template section of the sfc) so i'm not sure this will work because `regexVueTemplate` looks for `<template lang="pug">` but let me try...

**Comment by tjk** [comment]
Also there might be something wrong with the npm publishing? built `@unocss/extractor-pug` @ `0.6.2` doesn't have the changes?

**Comment by tjk** [comment]
```
test % npm init -y
Wrote to /private/tmp/test/package.json:

{
  "name": "test",
  "version": "1.0.0",
  "description": "",
  "main": "index.js",
  "scripts": {
    "test": "echo \"Error: no test specified\" && exit 1"
  },
  "keywords": [],
  "author": "",
  "license": "ISC"
}


tj@tjk-mbp test %
tj@tjk-mbp test % ls
package.json
tj@tjk-mbp test % npm install --save @unocss/extractor-pug@0.6.2
npm notice created a lockfile as package-lock.json. You should commit this file.
npm WARN test@1.0.0 No description
npm WARN test@1.0.0 No repository field.

+ @unocss/extractor-pug@0.6.2
added 1 package from 1 contributor and audited 1 package in 0.873s

1 package is looking for funding
  run `npm fund` for details

found 0 vulnerabilities

tj@tjk-mbp test % ls
node_modules      package-lock.json package.json
tj@tjk-mbp test % cat package.json
{
  "name": "test",
  "version": "1.0.0",
  "description": "",
  "main": "index.js",
  "scripts": {
    "test": "echo \"Error: no test specified\" && exit 1"
  },
  "keywords": [],
  "author": "",
  "license": "ISC",
  "dependencies": {
    "@unocss/extractor-pug": "^0.6.2"
  }
}
tj@tjk-mbp test % cat node_modules/@unocss/extractor-pug/dist/index.js
"use strict";Object.defineProperty(exports, "__esModule", {value: true});// src/index.ts
var regexVueTemplate = /<template.*?lang=['"]pug['"][^>]*?>\n([\s\S]*?\n)<\/template>/gm;
function extractorPug() {
  async function compile(code, id) {
    const Pug = await Promise.resolve().then(() => require("pug"));
    try {
      return Pug.compile(code, { filename: id })();
    } catch (e) {
    }
  }
  return {
    name: "pug",
    order: -1,
    async extract(ctx) {
      var _a, _b, _c;
      if ((_b = ctx.id) == null ? void 0 : _b.match(/\.vue$/)) {
```

**Comment by tjk** [comment]
Oh you have a syntax error I believe in that patch!

**Comment by davay42** [comment]
Pug support is very needed. I'm not skilled enough to contribute code, but I hope @tjk can figure it out soon. Thank you for the struggle!

**Comment by tjk** [comment]
Amazing!! I was starting on this patch... but taking it real slow. Thank you @antfu

**Comment by davay42** [comment]
@antfu Thank you for supporting pug! There seems to be one last issue: I'm using unocss just for css icons and they display fine at the DEV stage, but are absent in the BUILD bundle... I think it's related to pug too.

Here's my repo with the problem https://github.com/DeFUCC/project-app
