### ISSUE TITLE
Why not just a cli command?

### ISSUE THREAD

**Issue by xialvjun** [antfu/unocss#8]
just like https://github.com/acss-io/atomizer / https://acss.io/

**Comment by johannschopplich** [comment]
I have created a simple CLI, even with `unocss.config.js` support.

👉 [unocss-cli](https://github.com/johannschopplich/unocss-cli)

**Comment by antfu** [comment]
@johannschopplich that's great, awesome work! I am happy to have it as a part of this monorepo (if you want to) so we can ship it with the main package.

PS. for loading config, you can use `@unocss/config` for it which supports also `.ts`.

**Comment by johannschopplich** [comment]
@antfu Yes, I would absolutely love to integrate it into the monorepo. All in one place!
How do we continue?

Thanks for the tip, I have migrated to `@unocss/config`.

**Comment by antfu** [comment]
You can send a PR creating a new @unocss/cli package with your existing code (also have your license under the package!). I will help you handle the integrations and setup. Once merged, I will invite you to the repo. 🙌
