### ISSUE TITLE
Is it possible to extend preset customizing theme?

### ISSUE THREAD

**Issue by newfox79** [antfu/unocss#82]
For example I want to extend colors config to support our brand colors, i see this defined in theme file, so i can fork it and extend this way.
But I'm wondering if there are way to extend some theme configs without forking, 'cause now I have like two paths. Implementing own rule to handle our colors or, as mentioned above, forking and extending this way.

Is there are workaround, or I'm just missed something?

**Comment by antfu** [comment]
Yes, 

```ts
UnoCSS({
  theme: {
    textColors: { },
    // this will be deep merged to the default theme.
  },
  presets: [
    presetUno()
  ]
}
```

We will full fill the docs later.

**Comment by rashidpathiyil** [comment]
Not Working

```
    Unocss({
      theme: {
        textColors: {
          'very-cool': '#0000ff',
        }
      },
      presets: [
        presetAttributify({ /* preset options */ }),
        presetUno(),
        // ...custom presets
      ],
    })
```
