### ISSUE TITLE
Webpack and Nuxt 2 support

### ISSUE THREAD

**Issue by ram-you** [antfu/unocss#83]
Hi @antfu 
I really like the new approach of UnoCss which I find revolutionary and will become, I'm sure, the norm in the near future. 
However, I have a lot of projects running Nuxt2 and I would like to have an example (in pure Nuxt2 without the use of Vite). 
Thank you.

**Comment by antfu** [comment]
Currently, UnoCSS does not offer a Webpack plugin, which is unfortunately not my priority either. Before we starting working on it, PR would be great welcome if you want to give it a shoot

**Comment by ram-you** [comment]
Thank you @antfu for your response. 
Please leave this issue open for a while, to see the community's reactions.

**Comment by antfu** [comment]
They are supported v0.9

**Comment by 516310460** [comment]
Nuxt: 2.15.8
builder: Webpack

Error: Cannot find module 'uno.css'

Can you provide an `examples` of `Nuxt2 Webpack`. please
