### ISSUE TITLE
sr-only not working

### ISSUE THREAD

**Issue by lstegger** [antfu/unocss#84]
I hope I didn't get it wrong, but shouldn't the following work already?

`<div class="sr-only">Test</div>`

The text is still visible and no css is generated.

I found the rule here:
https://github.com/antfu/unocss/blob/e6c53687da7f073bd89d3a0e968f33a68de0fb63/packages/preset-uno/src/rules/static.ts#L125-L152

Reproduction:
https://unocss.antfu.me/?html=DwEwlgbgBAzgTgWgPYDsA2BPAfAKClAFQFMYAXHYAenAl1EigGM0BDGGAXgCJ5l0MuufMTIVqkLEA&config=JYWwDg9gTgLgBAbzgEwKYDNgDtUGEJaYDmcAvnOlBCHAOQCuWEAxgM6u0BQnqAHpLBQYAhvQA28NJhz5CwIgAoEnOHCjjUrAFxwA2itV7azeqxjUAtOrGpaAGkRxmEMdB20oqZLTIBdA-6kAJRAA&options=N4IgzgLgTglgxhEAuaBXApgXyA

I don't know if the playground is on latest unocss, but I guess so?!
I also tried it with vitesse-nuxt3, with unocss 0.6.4, where this rule should be included already. But still all sr-only elements are visible in browser. 

Please let me know, if more information is needed, I'm pretty new to this

**Comment by userquin** [comment]
@edwardnyc  seems you forgot to add it on `index.ts`

**Comment by edwardnyc** [comment]
> @edwardnyc seems you forgot to add it on `index.ts`

Emmm, yep, I guess my brain was down!!!
Forgot to apply after adding attributes......
